### ISSUE TITLE
Needs docs on how to configure UI session timeout

### ISSUE THREAD

**Issue by tooptoop4** [apache/incubator-superset#9956] opened 2020-06-01 10:30 UTC
Needs docs on how to configure UI session timeout

**Comment by tooptoop4** [comment] 2020-07-13 20:50
@dpgaspar any idea?

**Comment by dpgaspar** [comment] 2020-09-23 08:29
Duplicate of #10980, @tooptoop4 going to close this one, let's follow this question on @tooptoop4

**Closed by dpgaspar** 2020-09-23 08:29 UTC
Labels: #documentation, .pinned
