### ISSUE TITLE
Calendar heatmap labels hiding under the dashboard edge

### ISSUE THREAD

**Issue by bauchgefuhl** [apache/incubator-superset#3369] opened 2017-08-24 12:53 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.4

### Expected results
Labels are seen fully wherever they are located on heatmap.

### Actual results
![heatmap_problem](https://user-images.githubusercontent.com/3881689/29667163-0eb83d0a-88e4-11e7-9be3-d38ca8cc9ea7.png)

### Steps to reproduce
Run superset
Create calendar heatmap chart, check labels behaviour.

**Comment by xrmx** [comment] 2017-08-24 12:55
Duplicate of #3340, please close.

**Closed** 2017-08-24 13:59 UTC
