### ISSUE TITLE
Set user lockout after X amount of failed logins (prevent brute force attack)

### ISSUE THREAD

**Issue by larsmars** [apache/incubator-superset#10620] opened 2020-08-17 12:28 UTC
Set user lockout after X amount of failed logins to protect against bruteforce attacks.

- Feature toggle in config
- Configurable number of logins in config
- Admin can reset user (Is Active true/false)
- Email recovery link

**Comment by JunlinC** [comment] 2020-08-17 16:43
🏷 login

**Comment by nytai** [comment] 2020-10-22 04:51
This issue would make more sense in https://github.com/dpgaspar/Flask-AppBuilder as that's what's handling our login. You could also achieve this with a custom security manager, overriding the login method.

**Comment by nytai** [comment] 2020-10-22 04:51
also, duplicate of https://github.com/apache/incubator-superset/issues/10560

**Comment by willbarrett** [comment] 2020-10-26 23:00
Closing as duplicate.

**Closed by willbarrett** 2020-10-26 23:00 UTC
Labels: #enhancement, login
