### ISSUE TITLE
Version 0.20.0 not tagged and missing features?

### ISSUE THREAD

**Issue by joshwalters** [apache/incubator-superset#3555] opened 2017-09-29 19:09 UTC
- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.20.0

### Expected results

I expect to see features like `t-test table visualization` as called out in the [changelog](https://github.com/mistercrunch/superset/blob/8f59c18893f73a4aa0c368e387739967abd955be/CHANGELOG.md).

### Actual results

It looks like some features are not in the 0.20.0 release. Also, it looks like the 0.20.0 version was not tagged in git, so I don't know which tag to check to make sure the code is there.

**Comment by mistercrunch** [comment] 2017-09-29 23:50
Ooops, had created the tag but pushed it to my fork by mistake...
https://github.com/apache/incubator-superset/releases/tag/0.20.0

ttest should be in there as c629282ec4fe0b9e41d139183cdd3af48d4b55d2, let me know if that's not the case

**Comment by rjpereira** [comment] 2017-10-02 09:56
Clarifying : the 0.20.0 tag was still not committed, right?

**Comment by mistercrunch** [comment] 2017-10-02 15:38
Is some apache hook deleting it? I just re-pushed it...

**Comment by mistercrunch** [comment] 2017-10-02 15:39
<img width="932" alt="screen shot 2017-10-02 at 8 38 56 am" src="https://user-images.githubusercontent.com/487433/31085885-2fa127de-a74d-11e7-9f60-0d4f948927a2.png">

**Comment by rjpereira** [comment] 2017-10-02 16:40
Not sure what is going on but not visible:
![image](https://user-images.githubusercontent.com/643219/31088475-10a9aa0a-a7a1-11e7-8b81-8fabd92d2ecc.png)

**Comment by joshwalters** [comment] 2017-10-02 18:30
@mistercrunch This is very odd. If I go to the url for `0.20.0` it is giving a 404 error, and it doesn't show in the tag browser. Maybe something _is_ deleting it??

**Comment by kkalyan** [comment] 2017-10-03 00:23
not sure about the tags, but `pip install superset` does not install the latest code.

**Comment by mistercrunch** [comment] 2017-10-03 06:56
Something is deleting the branch/tag (I'm suspecting some apache hook). Could have to do the fact that `0.20.0` wasn't on the master branch somehow. I just created `0.20.1` which I will merge and tag once it's in master.

**Comment by xrmx** [comment] 2017-10-03 07:57
@kkalyan you probably have superset already installed and need --upgrade, it installed fine here

**Comment by rjpereira** [comment] 2017-10-03 08:42
As of now, I finally see the new releases/tags.

**Comment by joshwalters** [comment] 2017-10-03 18:21
Yep, looks like it is fixed now. Thanks @mistercrunch!

**Comment by rjpereira** [comment] 2017-10-04 01:18
Doesn't seem so :-( everything beyond 0.18 disappeared again ...

**Comment by joshwalters** [comment] 2017-10-04 18:16
It looks like the tags are being deleted again. 😞

**Comment by mistercrunch** [comment] 2017-10-04 18:49
![wack](https://user-images.githubusercontent.com/487433/31193856-1f6921ce-a8fa-11e7-8c3a-2d54e53ce1c2.gif)

**Comment by mistercrunch** [comment] 2017-10-04 18:54
I opened a ticket with ASF INFRA here:
https://issues.apache.org/jira/browse/INFRA-15218

**Comment by joshwalters** [comment] 2017-10-05 18:13
@mistercrunch It looks like they fixed the issue: https://issues.apache.org/jira/browse/INFRA-15218
🤞

**Comment by mistercrunch** [comment] 2017-10-06 07:43
Ok I just re-pushed the tags and hopefully Apache infra tackled the root cause. 🤞

**Closed by mistercrunch** 2017-10-06 07:43 UTC
