### ISSUE TITLE
Unable to start Super Set

### ISSUE THREAD

**Issue by pallaviMN** [apache/incubator-superset#10776] opened 2020-09-03 11:11 UTC
superset_tests_worker    | Unable to load celery application.
superset_tests_worker    | The module superset.tasks was not found.

**Comment by willbarrett** [comment] 2020-09-03 17:22
Please fill out all bug report information so that we may investigate the issue.

**Comment by nytai** [comment] 2020-09-23 03:00
closing as this is a duplicate of #10775

**Closed by nytai** 2020-09-23 03:00 UTC
Labels: #question, .install, need:more-info
