### ISSUE TITLE
Can we achieve "adding prefix to all superset routes" ?

### ISSUE THREAD

**Issue by thammaneni** [apache/incubator-superset#10063] opened 2020-06-16 10:08 UTC
I am trying to add default prefix to all superset route points but there are many places route points are hard coded is there any way we can fix this or already fixed?
The below link might give you more explanation, i am not sure whether superset has fix for this or not. Can you guys please throw some ideas here if it is achievable? 
=> Ref : https://github.com/apache/incubator-superset/issues/3690

=> https://stackoverflow.com/questions/18967441/add-a-prefix-to-all-flask-routes/36033627#36033627

### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by lexisstv** [comment] 2020-06-21 10:38
Yeah. I'm spend 2 days to modify all direct links for move superset to subpath (except tests)... Glad if this will be fixed...

**Comment by willbarrett** [comment] 2020-06-24 22:08
I've seen this issue crop up a number of times, and I think the problem is that we do not have contributors from organizations where this is an issue. We would, however, be open to a PR that introduces the feature. @lexisstv if you've made the updates in code already and would be willing to share that as a PR it would help us understand the scope required for the change. I'd be happy to support a new contributor who wants to make this enhancement.

**Comment by lexisstv** [comment] 2020-07-07 07:58
Unfortunately, I'm new to python, and not sure about the quality of my hotfixes. I’ll try to find the time to arrange the PR.

**Comment by mistercrunch** [comment] 2020-07-08 05:51
One good place to start would be to use `flask.url_for` for all hard coded url paths on the backend. Then there's a need to do some flask trickery  to add a prefix to all existing routes (not sure whether that's easy and how hacky it would be, but likely fairly hacky). Then the frontend needs to get that prefix and use it to all routes as well.

**Comment by summerswallow-whi** [comment] 2020-07-13 17:02
I'm very interested in this issue. Seems from what I've read, that for some organization this could be a make or break reason to use Superset as might be the case for my organization as well. Seeing what transpired in the PR#3690. I would suggest multiple PR. I think the part of the reason it failed is because they were trying to fix the whole problem at once and since the project progressed with hundreds of PR during the time resolving conflicts became a great burden. 

Seems that even if all the PR does is converts to `flask.url_for` that is a better coding practice than hard coded paths could be the first PR. This would be a code quality enhancement rather than feature enhancement. Once in you start taking on the next problem.

**Comment by lexisstv** [comment] 2020-09-13 12:09
Please, don't close this

**Comment by bryantjcb** [comment] 2020-12-10 09:28
Is there any update about this issue?

**Closed** 2020-12-16 05:50 UTC
Labels: #question
