### ISSUE TITLE
Dashboard date filter - constantly displays infinity range

### ISSUE THREAD

**Issue by DaimonPl** [apache/incubator-superset#3650] opened 2017-10-11 09:39 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x ] I have reproduced the issue with at least the latest released version of superset
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.20.3

### Expected results
Upon changing dashboard filtering, icons should indicate new range

### Actual results
Since ∞
Until ∞

### Steps to reproduce
1. Add date filter to dashboard
2. Change range

**Comment by DaimonPl** [comment] 2017-10-11 11:33
And here's image

![filter_infinity](https://user-images.githubusercontent.com/9693936/31438537-b957b15e-ae88-11e7-88e8-2cb4f2eff986.png)

**Comment by rumbin** [comment] 2017-10-11 17:26
I believe this is a duplicate of #3610 which is set to closed already. I don't see any PR associated with it, though.

**Comment by mistercrunch** [comment] 2017-10-12 04:09
Pushing `v0.20.4` now with the fix, should be out in a few minutes

**Closed by mistercrunch** 2017-10-12 04:09 UTC
