### ISSUE TITLE
Dashboard time range filter rendering bug

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#10471] opened 2020-07-29 16:46 UTC
The time range filter in dashboard is too small, squeezing relative date range inputs.

#### Screenshots

<img src="https://user-images.githubusercontent.com/335541/88828390-064dc300-d180-11ea-96b3-49a2c6eec953.png" width="300">

#### How to reproduce the bug

1. Create a filterbox with time range filter
2. Add it to a dashboard

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by ktmud** [comment] 2020-07-29 21:59
<img src="https://user-images.githubusercontent.com/335541/88857978-1b404b80-d1ac-11ea-828c-2d2ebc4ac344.png" width="120" >

Similar issue in SQL Lab

**Comment by mistercrunch** [comment] 2020-08-06 00:02
Related to https://github.com/apache/incubator-superset/pull/10302 ?

**Comment by rusackas** [comment] 2020-08-06 04:14
Potentially related to that... or something else from the recent bash, perhaps. I'm not available until Monday, but have self assigned this issue to fix when I return, unless anyone else tackles it first :)

**Comment by avicenteg** [comment] 2020-09-16 08:47
Hi,
Do you have any news related with this issue? @rusackas @mistercrunch 
I think it's related with the "withTheme" function used for export the DateFilter component.

**Comment by kkucharc** [comment] 2020-10-25 10:34
Hi @ktmud @avicenteg, do you know if this issue is still happening? I'm checking it on chrome and it looks like it was solved in meantime:
<img width="520" alt="Screenshot 2020-10-25 at 11 20 42" src="https://user-images.githubusercontent.com/2536609/97104648-dc8c3580-16b5-11eb-974b-049673ececfa.png">
<img width="302" alt="Screenshot 2020-10-25 at 11 26 36" src="https://user-images.githubusercontent.com/2536609/97104653-e3b34380-16b5-11eb-8120-669178141869.png">

**Comment by junlincc** [comment] 2020-10-25 16:36
@kkucharc This is happening on Dashboard time range filter, not in Explore, I can confirm that this is still an issue. reach out to me directly if it's unclear. thanks!
<img width="1186" alt="Screen Shot 2020-10-25 at 9 33 44 AM" src="https://user-images.githubusercontent.com/67837651/97113091-54059900-16a5-11eb-8924-d83954ce8717.png">

**Comment by avicenteg** [comment] 2020-10-26 14:24
> @kkucharc This is happening on Dashboard time range filter, not in Explore, I can confirm that this is still an issue. reach out to me directly if it's unclear. thanks!
> <img alt="Screen Shot 2020-10-25 at 9 33 44 AM" width="1186" src="https://user-images.githubusercontent.com/67837651/97113091-54059900-16a5-11eb-8924-d83954ce8717.png">

There is any intention of fixing this?  I see that you're working in preset, so maybe you know something...

**Closed** 2020-10-27 04:53 UTC
Labels: #bug, cosmetic-issue, polidea
