### ISSUE TITLE
Portuguese Translation Doesn't Translate Everything

### ISSUE THREAD

**Issue by csc5k** [apache/incubator-superset#5148] opened 2018-06-06 11:45 UTC
### Superset version
0.24.0

### Expected results
All tabs, non-data words (e.g. "since" and "until," month names) are translated to Portuguese

### Actual results
Only the Security tab is translated
![image](https://user-images.githubusercontent.com/33062840/41036261-2b9c860c-6998-11e8-8172-afff9c74aa38.png)

**Comment by xrmx** [comment] 2018-06-06 12:11
Please reproduce with 0.25 or master

**Comment by claycrosby** [comment] 2018-06-08 08:06
Thanks, I upgraded and some more buttons are translated but still not all. What I can see that needs to be translated:

Months:
![image](https://user-images.githubusercontent.com/33062840/41146384-cc0bb684-6b0b-11e8-8c04-7e81fde89304.png)

"Charts" and "Dashboards":
![image](https://user-images.githubusercontent.com/33062840/41146393-d5e5d266-6b0b-11e8-9282-e9bfec265609.png)

Edit/View dashboard and Actions dropdown:
![image](https://user-images.githubusercontent.com/33062840/41146408-e3e3c454-6b0b-11e8-8feb-6d11bcd0f979.png)

"Since" and "Until" in a date filter:
![image](https://user-images.githubusercontent.com/33062840/41146425-f4842eb6-6b0b-11e8-8396-944f3a14f544.png)

Tooltips when hovering over buttons:
![image](https://user-images.githubusercontent.com/33062840/41146448-06bf54ca-6b0c-11e8-83c6-3eee4d787006.png)

**Comment by claycrosby** [comment] 2018-06-08 08:12
Is there a translation file somewhere? We have a team in Mozambique who is fluent in Portuguese, so they could contribute to closing these gaps

**Comment by mistercrunch** [comment] 2018-06-08 15:27
Instructions:
https://github.com/apache/incubator-superset/blob/master/CONTRIBUTING.md#translations

File:
https://github.com/apache/incubator-superset/blob/master/superset/translations/pt_BR/LC_MESSAGES/messages.po

**Closed** 2018-07-30 07:19 UTC

**Comment by SWoto** [comment] 2019-10-25 11:23
Is there a way to translate the time_range filter? When I change the names inside the DateFilterControl.jsx to t(English) it displays the Portuguese words, but the filter doesn't work. I think it is because the moment (eg. `moment().startOf('day').subtract(1, units).format(MOMENT_FORMAT)`) only works with English words.

**Comment by KevenLee229** [comment] 2019-11-09 04:33
I think you should apply t function to the constant. @SWoto 
e.g.
`const TIME_GRAIN_OPTIONS = [t('seconds'), t('minutes'), t('hours'), t('days'), t('weeks'), t('months'), t('years')];
`
