### ISSUE TITLE
Chart Explore: Pasting text into Metrics fails and deletes other metrics

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11379] opened 2020-10-22 01:13 UTC
Pasting text into Metrics fails and deletes other metrics. This feature is commonly used if metrics are long - user finds them in documentation / from a colleague (via slack) / from previous chart - instead of typing the metric name user wants to paste it. This functionality worked at some point in the past.

### Expected results

Existing metric remain, and newly pasted metric (if exists) also is in the Metrics field.

### Actual results

Existing metrics disappear. 

#### Screenshots
Step 1: There is some metric in the METRICS field.
<img width="485" alt="Screen Shot 2020-10-21 at 6 08 15 PM" src="https://user-images.githubusercontent.com/61221714/96806417-def64300-13c8-11eb-8fd2-4db017471a27.png">

Step 2: try to paste new metric, like "test_metric"

Step 3: All metrics disappear. Regardless of if metric that is being pasted exists or not.
<img width="475" alt="Screen Shot 2020-10-21 at 6 08 42 PM" src="https://user-images.githubusercontent.com/61221714/96806409-dbfb5280-13c8-11eb-84b5-7eaa8cad5063.png">

#### How to reproduce the bug

1. Go to 'Chart Explore'
2. Click in 'Metrics field'
3. Paste name of a metric, for example try to paste 'test_metric'
4. See issue - all existing metrics disappear

### Environment

(please complete the following information):

- superset version: `master`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment] 2020-10-22 15:29
@zuzana-vej could you please provide a gif that shows the old behavior? do you think [#11388](https://github.com/apache/incubator-superset/issues/11388) are caused by a same PR?

**Comment by zuzana-vej** [comment] 2020-10-22 16:21
I can't provide video of old behavior (when pasting a metric into the box worked) because old behavior doesn't work right now (honestly I am not sure how long this has been broken, this might not be feature user uses every day, so it could be couple weeks). 

I think they certainly touch the same component, so the regression is likely to be introduced when doing some redesign/changes to the Metrics box.

**Comment by kgabryje** [comment] 2020-10-26 17:39
Can you assign me please?

**Comment by junlincc** [comment] 2020-10-26 17:57
> Can you assign me please?

added to Trello and assigned to you~

**Comment by junlincc** [comment] 2020-11-04 06:16
tested~fixed.  closing issue thanks! @kgabryje

**Closed by junlincc** 2020-11-04 06:16 UTC
Labels: #bug, .explore, polidea
