### ISSUE TITLE
series limit put to 0 results in no subquery but gives stupid parsing error (on postgre ?)

### ISSUE THREAD

**Issue by maartenvanwauwe** [apache/incubator-superset#3463] opened 2017-09-14 14:29 UTC
version:0.19.1
if I set the series limit to 100 -> query works
SELECT tenant AS tenant,
       ymd_ts AS __timestamp,
       SUM(myschema.marathonreservation.weightedtotal) AS sum__weightedtotal
FROM myschema.marathonreservation
JOIN
  (SELECT tenant AS tenant__,
          SUM(myschema.marathonreservation.weightedtotal) AS mme_inner__
   FROM myschema.marathonreservation
   WHERE ymd_ts >= '1917-09-14 00:00:00'
     AND ymd_ts <= '2017-09-14 14:21:08'
   GROUP BY tenant
   ORDER BY mme_inner__ DESC
   LIMIT 100) AS anon_1 ON tenant = tenant__
WHERE ymd_ts >= '1917-09-14 00:00:00'
  AND ymd_ts <= '2017-09-14 14:21:08'
GROUP BY tenant,
         ymd_ts
ORDER BY sum__weightedtotal DESC
LIMIT 5000

if I remove the series limit (by putting on 0) -> '>' not supported between instances of 'str' and 'int'
SELECT tenant AS tenant,
       ymd_ts AS __timestamp,
       SUM(myschema.marathonreservation.weightedtotal) AS sum__weightedtotal
FROM myschema.marathonreservation
WHERE ymd_ts >= '1917-09-14 00:00:00'
  AND ymd_ts <= '2017-09-14 14:21:35'
GROUP BY tenant,
         ymd_ts
ORDER BY sum__weightedtotal DESC
LIMIT 5000

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 251, in get_payload
    data = self.get_data(df)
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 916, in get_data
    df = self.process_data(df)
  File "/usr/local/lib/python3.6/site-packages/superset/viz.py", line 865, in process_data
    values=fd.get('metrics'))
  File "/usr/local/lib/python3.6/site-packages/pandas/core/reshape/pivot.py", line 160, in pivot_table
    table = table.sort_index(axis=1)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/frame.py", line 3243, in sort_index
    labels = labels._sort_levels_monotonic()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 1240, in _sort_levels_monotonic
    indexer = lev.argsort()
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2091, in argsort
    return result.argsort(*args, **kwargs)
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by xrmx** [comment] 2017-09-14 14:36
First please follow the issue template, second this is a duplicate of #3029 so close.

**Closed** 2017-09-14 14:41 UTC
