### ISSUE TITLE
I want to add some chart style, such as linePlusBarChart, multiBarHorizontalChart, multiChart

### ISSUE THREAD

**Issue by ujhujuh** [apache/incubator-superset#1768] opened 2016-12-06 03:06 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [yes ] I have checked the superset logs for python stacktraces and included it here as text if any
- [yes ] I have reproduced the issue with at least the latest released version of superset
- [yes] I have checked the issue tracker for the same issue and I haven't found one similar

In our project , we enhance the viz that add some chart style :  linePlusBarChart, multiBarHorizontalChart, multiChart.
we can get the chart like that:
![a](https://cloud.githubusercontent.com/assets/19641641/20911499/5ada52e0-bba3-11e6-83ff-6d51de45837d.png)
![b](https://cloud.githubusercontent.com/assets/19641641/20911501/5c0c0866-bba3-11e6-9380-b595ee40c692.png)
![c](https://cloud.githubusercontent.com/assets/19641641/20911503/5d4dd434-bba3-11e6-88d6-5821cd320956.png)

### Superset version
0.14.1

### Expected results
1.linePlusBarChart
2. multiBarHorizontalChart,
3.multiChart.

### Actual results
fine

### Steps to reproduce
New feature.

later, I will submit the code, ,if you think my code is okay, could you please merge pull reqiest?

**Comment by mistercrunch** [comment] 2016-12-06 04:35
note that we have the `explorev2` refactor going on (to be merged probably end of week), until it's merged you need to make the changes in 2 places (explore and explorev2).

From the screenshot about, the 3rd chart looks pretty unreadable...

the 2nd chart seems like it could just be a new `is_horizontal` option added to the existing bar chart (if the api is similar enough)

**Comment by ujhujuh** [comment] 2016-12-06 05:51
@mistercrunch 
i think the 3nd chart  is necessary，I was able to get any charts I wanted。
It looks unreadable because there are too many charts, you can choose what you want.
like that:
![d](https://cloud.githubusercontent.com/assets/19641641/20914432/8ef3ab6e-bbba-11e6-8b56-e50da294251b.png)
![e](https://cloud.githubusercontent.com/assets/19641641/20914434/937ff34a-bbba-11e6-90f5-4c705afa61c6.png)

**Comment by desavera** [comment] 2017-06-28 17:15
This would be GREAT !

**Comment by gremney** [comment] 2017-09-01 08:22
This looks amazing. I am using version 0.19 but seems could not reproduce the above. I am also unable to locate the "chart options" in superset, could you please advise? Appreciated.

**Comment by shyam2794** [comment] 2017-10-05 10:11
@ujhujuh  This looks great and will be very much usefull in our current project. Can you please document the steps how you have implemented this, it will be much helpfull .

**Comment by mistercrunch** [comment] 2017-10-05 16:09
FYI we're considering [longer term] to move our core charts to using `data-ui` which is built on `vx`. These charts are very "composable" meaning we could add better support for multi-layered charts at that point. Until then I don't think we want to add much more support for multi-layered-charts.

**Comment by mistercrunch** [comment] 2018-04-23 15:31
Notice: this issue has been closed because it has been inactive for 199 days. Feel free to comment and request for this issue to be reopened.

**Comment by kristw** [comment] 2019-02-13 13:07
#6812

**Closed by kristw** 2019-02-13 13:07 UTC
