### ISSUE TITLE
Error while installing (markdown() takes 1 positional argument but 2 were given)

### ISSUE THREAD

**Issue by JvnB** [apache/incubator-superset#5958] opened 2018-09-22 16:35 UTC
- [X ] I have checked the superset logs for python stacktraces and included it here as text if any
- [X ] I have reproduced the issue with at least the latest released version of superset
- [X ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
dev and release 0.27.0

### Expected results
Installed superset 

### Actual results
Error while installing:
Was unable to import superset Error: markdown() takes 1 positional argument but 2 were given

### Steps to reproduce
Followed the instructions for a fresh (docker) installation:

```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
cp contrib/docker/{docker-build.sh,docker-compose.yml,docker-entrypoint.sh,docker-init.sh,Dockerfile} .
cp contrib/docker/superset_config.py superset/
bash -x docker-build.sh
docker-compose up -d
docker-compose exec superset bash
bash docker-init.sh
```

at the last command after the username/usermail/ password are asked for input the installation fails.
Reproduced on two different laptops

Additionally, when not using the docker installation. It fails at the same step:
`fabmanager create-admin --app superset` (which is done in the docker installation in the bash docker-init.sh script)

Trace:

```
xxx@xxx-server:~/dev/compose/incubator-superset$ docker-compose exec superset bash
work@3d443226a074:~/incubator-superset$ bash docker-init.sh
+ fabmanager create-admin --app superset
Username [admin]: xxx
User first name [admin]: xxx
User last name [user]: xxx
Email [admin@fab.org]: xxx@xxx.com
Password: 
Repeat for confirmation: 
Loaded your LOCAL configuration at [/home/work/incubator-superset/superset/superset_config.py]
Was unable to import superset Error: markdown() takes 1 positional argument but 2 were given

```

**Comment by jcmcken** [comment] 2018-09-22 23:11
I ran into this too just a few moments ago. There's a bug in ``/home/work/incubator-superset/superset/utils.py`` within the Docker image. This patch fixes the issue:

```diff
--- /tmp/utils.py	2018-09-22 23:09:23.168916170 +0000
+++ /home/work/incubator-superset/superset/utils.py	2018-09-22 23:09:28.559916297 +0000
@@ -420,7 +420,7 @@
                           'li', 'dd', 'dt', 'img', 'a']
     safe_markdown_attrs = {'img': ['src', 'alt', 'title'],
                            'a': ['href', 'alt', 'title']}
-    s = md.markdown(s or '', [
+    s = md.markdown(s or '', extensions=[
         'markdown.extensions.tables',
         'markdown.extensions.fenced_code',
         'markdown.extensions.codehilite',
```

**Comment by nunohelibeires** [comment] 2018-09-23 01:43
I am also getting this error and already tried the docker and the py venv installation... help needed indeed

**Comment by JvnB** [comment] 2018-09-23 09:11
@jcmcken fix worked

**Comment by victornoel** [comment] 2018-09-24 10:15
The problem is that superset depends on markdown==2.6.11 but for a reason I'm not clear about, v3 is installed in the docker image.

**Comment by victornoel** [comment] 2018-09-24 10:16
Ah yes, the docker install is using `setup.py` which does not specify a version for `markdown`.

This is where this should be fixed.

**Comment by victornoel** [comment] 2018-09-24 11:04
For the record I'm working on improving the developer experience with the docker image, and will soon make a PR that will fix this situation.

**Comment by JvnB** [comment] 2018-09-24 11:17
Thanks, nb. it was not only the docker image in which the problems occured. Normal installation had the same problem.

**Comment by victornoel** [comment] 2018-09-24 12:03
@JvnB you are right, this should be fixed in `setup.py` by putting a constraint on the markdown dependency (`<3.0.0`).

**Comment by victornoel** [comment] 2018-09-24 12:12
I have submitted a PR for this problem (#5967)

**Comment by shobhitverma** [comment] 2018-09-24 18:29
That was very helpful. Trying superset for the first time and already the first bug has resolution on github. Great job!

**Closed** 2018-09-24 18:41 UTC

**Comment by hamidmahmoodnbs** [comment] 2018-09-26 10:33
I am facing the same error when I am installing superset using pip install superset. When I create-admin the following error occurs. I am using python3.6 and pip 18. Please help me

$ fabmanager create-admin --app superset
Username [admin]: admin	
User first name [admin]: admin
User last name [user]: user
Email [admin@fab.org]: admin@fab.org
Password: 
Repeat for confirmation: 

Was unable to import superset Error: markdown() takes 1 positional argument but 2 were given

**Comment by victornoel** [comment] 2018-09-26 11:32
@hamidmahmoodnbs you need to either wait for a new release of superset.
Until then you can install it like this so that the version of markdown is forced to a working version:
```
$ pip install "markdown<3.0.0" superset
```

**Comment by hamidmahmoodnbs** [comment] 2018-09-26 11:56
Thanks Victor I have installed the older version of superset 0.22.0. It is
working fine for me.

Thanks

**Comment by krzyzakp** [comment] 2018-09-26 12:19
@hamidmahmoodnbs downgrade your markdown package - superset is not working with markdown >=3.0
Just run:  `pip install -U markdown==2.6.11`

**Comment by shaikidris** [comment] 2018-09-27 17:51
Thanks Victor, we were trying it on ubuntu box for the first time and did not have a good experience with the setup, nonetheless the forced markdown version helped.

**Comment by abshammeri** [comment] 2018-09-28 23:30
Thanks @victornoel , but not sure what is the purpose of setup.py if we already have requirements.txt? I agree with you that the docker needs a revision too.

**Comment by victornoel** [comment] 2018-09-29 06:44
@abshammeri you should read on the matter, for example https://caremad.io/posts/2013/07/setup-vs-requirement/

I have submitted a PR to improve the docker image: #5966

**Comment by ujwal-narayan** [comment] 2018-10-04 20:47
Had got the same error even with `mardown<3.0`. The issue was with the Flask version with Flask App Builder which superset is built on not supporting versions greater than 0.12.1 . `pip install flask==0.12.1  ` fixed the issue for me .
