### ISSUE TITLE
% in sql lab causes csv download error

### ISSUE THREAD

**Issue by kespindler** [apache/incubator-superset#2880] opened 2017-06-01 00:00 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
18.2

### Expected results
I can download a csv for my query

### Actual results
Pressing download csv causes a 500 error

### Steps to reproduce

I try to run a query in sql lab similar to following 

```
SELECT email
FROM users
WHERE email not ilike '%gmail.com'
```

The query works, but when I go to download a csv, it fails with  `*** TypeError: 'dict' object does not support indexing`. Digging around, I found: https://stackoverflow.com/questions/3944276/psycopg2-using-wildcard-causes-typeerror

This bug can be addressed by doubling the percents:

```
I try to run a query similar to following 
SELECT email
FROM users
WHERE email not ilike '%%gmail.com'
```

but users shouldn't have to know python internals to download csvs of their sql queries.

**Comment by cyaolong** [comment] 2018-01-12 06:56
My query to run in SQL-Lab is like this:
```
SELECT * FROM test.Game
WHERE Name like 'QQ%'
```

And it fails with "unsupported format character ''' (0x27) at index 45". 
What does this mean? Why couldn't it runs with a "%"?

**Comment by kespindler** [comment] 2018-01-12 07:10
@cyaolong Try doubling up the %. 

```
SELECT * FROM test.Game
WHERE Name like 'QQ%%'
```

**Comment by hajdbo** [comment] 2019-03-28 03:46
This has been fixed since you opened this issue.
Please close this issue.
Confirmed with 0.29.0rc7, today.

**Comment by hajdbo** [comment] 2019-04-03 08:38
@kristw please close: fixed.

**Closed** 2019-04-03 19:08 UTC
Labels: #bug, resolved
