### ISSUE TITLE
SQL Lab horizontal resizer can be dragger past the bottom of the page

### ISSUE THREAD

**Issue by john-bodley** [apache/incubator-superset#7383] opened 2019-04-25 17:31 UTC
In SQL Lab one can drag the horizontal resizer off the bottom of the page and there's no way to re-drag the resizer back. One needs to reload the page in order for the resizer to be repositioned.

### Expected results

One should not be able to drag the resizer past the bottom of the page.

### Actual results

It seems in some circumstances the resizer can be dragged past the bottom of the page and thus not recovered.

#### Screenshots

![sql-lab-resizer-issue](https://user-images.githubusercontent.com/4567245/56755458-6e735500-6744-11e9-9ae4-2e7f21630768.gif)

#### How to reproduce the bug

1. Go to SQL Lab.
2. Drag the horizontal resizer past the bottom of the page (and release the mouse click). 
3. Observe there is no way to drag the resizer back.

### Environment

(please complete the following information):

- superset version: 0.31.0rc23 (Note this may be fixed in `master`).
- python version: 3.6.8
- node.js version: v10.15.0
- npm version: 6.4.1

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

to: @enricoberti @vylc @xtinec

**Comment by michellethomas** [comment] 2019-05-24 23:06
This looks like it's fixed in master

**Comment by mistercrunch** [comment] 2019-05-25 00:11
That's right, couldn't reproduce this one in `master`

**Closed** 2019-05-25 00:13 UTC
Labels: #bug
