### ISSUE TITLE
Type filter in Dataset CRUD view doesn't work

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#11266] opened 2020-10-14 16:16 UTC
When I select "Physical" as the dataset type I still get virtual datasets

### Expected results
Only get physical dataset types

### Actual results
Also get virtual datasets

#### Screenshots

![image](https://user-images.githubusercontent.com/7409244/96016580-c3ee6680-0dfd-11eb-9046-1921c33acd4d.png)

**Comment by dpgaspar** [comment] 2020-10-14 17:37
@etr2460 I'm not being able to reproduce this. The filter applies to `is_sqllab_view`

**Comment by nytai** [comment] 2020-10-14 21:51
I'm also unable to reproduce. @etr2460 are some of these datasets using the native druid connector? It's possible the [logic that determines the datasets type](https://github.com/preset-io/incubator-superset/blob/master/superset/connectors/base/models.py#L115) is incorrectly implemented for druid datasources. As @dpgaspar mentioned the actual filtering logic is applied to the `is_sqllab_view` attribute.

**Comment by etr2460** [comment] 2020-10-27 16:13
@dpgaspar, @nytai: I can still repro this, even with Presto datasources. However, it looks like the ones that get filtered as Physical but are labeled as Virtual have custom sql added to them. Perhaps that needs to be part of the filtering logic too?

**Comment by nytai** [comment] 2020-10-27 16:59
@etr2460 is the issue here that physical datasets are incorrectly labelled as virtual, or that the filter logic is not accounting for other instances/types of virtual datasets?

**Comment by etr2460** [comment] 2020-10-27 23:25
I think it's the later. The datasets seem to be correctly labeled as Virtual, but they still show up when you filter to Physical only datasets

**Comment by nytai** [comment] 2020-10-28 01:41
ok, I see what the discrepancy is here. The label of "Physical" and "Virtual" is based on the presence of the `sql` attribute (see https://github.com/apache/incubator-superset/blob/155b5edec131d71eb392ee52f9bf97de495c2ef0/superset/connectors/base/models.py#L116). Meanwhile the filter for "Physical" and "Virtual" is based on the `is_sqllab_view` flag (see https://github.com/apache/incubator-superset/blob/155b5edec131d71eb392ee52f9bf97de495c2ef0/superset-frontend/src/views/CRUD/data/dataset/DatasetList.tsx#L353). 

So the question is, which attribute determines if it's a "virtual" dataset? The presence of the `sql` attribute or the `is_sqllab_view` attribute?

**Comment by nytai** [comment] 2020-10-28 01:50
hmmm, looks like `is_sqllab_view` only exists for sqla datasources

**Comment by nytai** [comment] 2020-10-29 20:12
@etr2460 can you confirm this was fixed by #11452 when you get a chance?

**Closed** 2020-10-29 20:11 UTC
Labels: #bug
