### ISSUE TITLE
Default credential not working

### ISSUE THREAD

**Issue by SwapnilKhante** [apache/incubator-superset#10149] opened 2020-06-24 07:59 UTC
### Expected results
Successful login

what you expected to happen.

### Actual results
Trying admin username and admin as password. Getting
Invalid login. Please try again.

what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/26261691/85518942-6ea80280-b61e-11ea-8f98-543ec1c98782.png)

### Environment

(please complete the following information):

Running docker setup

**Comment by SwapnilKhante** [comment] 2020-06-24 09:35
![image](https://user-images.githubusercontent.com/26261691/85529264-7e2d4880-b62a-11ea-9b39-0fc5debafb8d.png)

**Comment by SwapnilKhante** [comment] 2020-06-24 09:36
Its similar issue as 
https://github.com/apache/incubator-superset/issues/7336, but none of the solution mentioned worked.

**Comment by scook12** [comment] 2020-06-24 14:48
Is there a reason this was closed? I'm still having this issue.

**Comment by SwapnilKhante** [comment] 2020-06-24 15:18
@scook12 I could manage to fix this issue.
You need to run following command to setup username and password:
 docker-compose exec superset bash /app/docker-init.sh

If you run it in windows you will get an error. To fix it first run following
dos2unix docker-init.sh 
This will make the script linux ready as the script got copied from windows system to a linux one and it has certain special characters which throws errors.

**Comment by scook12** [comment] 2020-06-24 15:44
Got it, thanks @SwapnilKhante!

**Comment by simondmorias** [comment] 2020-06-27 15:50
I do not agree this issue should be closed. The documents for Docker clearly state the user/password should be admin/admin. 
But this is incorrect (https://superset.incubator.apache.org/installation.html#start-with-docker).
This is a big off put with wanting to try Superset.

**Comment by SwapnilKhante** [comment] 2020-06-28 09:52
@simondmorias I agree. It does not work the way it is mentioned in official documentation.
Reopening the issue.

**Comment by edurojasr** [comment] 2020-07-08 21:18
Hi all

+1 should not be closed, the documentation doesn't mention this step

Thanks @SwapnilKhante!!

**Comment by DanielGeffers** [comment] 2020-07-09 13:24
I still fail to get superset up on windows. I ran 
dos2unix docker-init.sh
and then 
docker-compose exec superset bash /app/docker-init.sh

But I get the error

ERROR: No container found for superset_1

**Comment by DanielGeffers** [comment] 2020-07-11 18:33
@SwapnilKhante 

how exacly did you call it on windows?
When I run first 
docker-compose up
and then 
docker-compose exec superset bash /app/docker-init.sh
in a different terminal, nothing happens exept for a second of computation.

**Comment by ToryZhou** [comment] 2020-07-28 12:21
To init the user and roles
sudo docker-compose exec superset bash /app/docker-init.sh

**Comment by jessecbrown** [comment] 2020-08-05 12:40
when trying to init the roles as @ToryZhou suggested I'm presented with the following error:

```
######################################################################


Init Step 1/4 [Starting] -- Setting up admin user ( admin / admin )


######################################################################

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 6, in <module>
    with open(__file__) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/superset/bin/superset'
```

**Comment by Chardonneaur** [comment] 2020-08-05 19:28
I am confirming @jessecbrown message, so to say the Docker image is currently useless.

**Comment by idkw** [comment] 2020-08-05 21:49
Same issue

**Comment by cande1gut** [comment] 2020-08-06 22:27
I was having the same problem. I end up using their image: [https://hub.docker.com/r/preset/superset/](url) with a custom extension as they point at the bottom of the page and it worked.

**Comment by nathan-protempo** [comment] 2020-08-07 03:15
I also have this issue. Followed the steps at https://superset.apache.org/installation.html#start-with-docker, the default login of admin/admin does not work (Get: "Invalid login. Please try again").

All 4 containers appear to be running after running docker-compose up.

Environment: 
Windows 10 (version 1909)
Docker 19.03.12

dos2unix docker-init.sh
This doesn't work in Powershell. Ran in Git Bash, in root folder (incubator-superset) - get "No such file or directory"

docker-compose exec superset bash /app/docker-init.sh
Get "the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'"

**Comment by mistercrunch** [comment] 2020-08-07 05:27
Is everyone here on Windows?

**Comment by idkw** [comment] 2020-08-07 11:07
No same issue on Linux mint

**Comment by Chardonneaur** [comment] 2020-08-07 14:01
Ubuntu.

**Comment by craig-rueda** [comment] 2020-08-07 15:48
Yep, I just ran a clean `up` and I'm seeing:

```
Traceback (most recent call last):
   File "/usr/local/bin/superset", line 6, in <module>
     with open(__file__) as f:
 FileNotFoundError: [Errno 2] No such file or directory: '/app/superset/bin/superset'
```
I'll get a fix for this today :)

**Comment by PhucNgo1711** [comment] 2020-08-07 21:56
> ```
> Traceback (most recent call last):
>    File "/usr/local/bin/superset", line 6, in <module>
>      with open(__file__) as f:
>  FileNotFoundError: [Errno 2] No such file or directory: '/app/superset/bin/superset'
> ```
I'm having this issue on macOS too. And this is after running dos2unix.

**Comment by alittlesliceoftom** [comment] 2020-08-07 23:43
Also having this issue. (windows)

On running: 
```docker-compose up```
and then
```docker-compose exec superset bash /app/docker-init.sh```

The command fails to create the admin user

**Closed** 2020-08-09 01:56 UTC
Labels: #bug, .docker

**Comment by PhucNgo1711** [comment] 2020-08-09 05:46
I just re-cloned the repo again but the issue is still there.

**Comment by craig-rueda** [comment] 2020-08-09 15:48
Please nuke your images and volumes:

```
# Nukes containers:
docker rm -f $(docker ps -aq | awk '{print $1}')

# Nukes images:
docker rmi -f $(docker images | awk '{print $3}') 

# Nukes volumes:
docker-compose down -v

# Re-Builds docker-compose:
docker-compose build

# Stand everything back up:
docker-compose up
```

Hope that helps!

**Comment by PhucNgo1711** [comment] 2020-08-09 17:46
Yes it did. Thank you!

**Comment by craig-rueda** [comment] 2020-08-10 00:14
BTW, i have the first two CMDs setup as aliases in my `.zshrc` as they're super useful.

**Comment by idkw** [comment] 2020-08-24 07:55
@craig-rueda 

This is still not working for me after nuking everything :(

I was really eager to test this promising tool. Do we have a workaround for it with docker ? Thanks !

```
val@val-GL702VT ~/dev/incubator-superset $ docker exec -it superset_app bash
superset@36445bfe7eae:/app$ cd /^C
superset@36445bfe7eae:/app$ ls
MANIFEST.in  README.md	apache_superset.egg-info  docker-init.sh  pythonpath  requirements  requirements-dev.txt  requirements-extra.txt  requirements.txt  setup.py  superset	superset-frontend  superset_home
superset@36445bfe7eae:/app$ ./docker-init.sh 

######################################################################


Init Step 1/4 [Starting] -- Setting up admin user ( admin / admin )


######################################################################

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 6, in <module>
    with open(__file__) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/app/superset/bin/superset'


```

**Comment by craig-rueda** [comment] 2020-08-24 15:40
This is fixed in master. Please make sure you are up to date and have cleared all of your images, containers and volumes.

**Comment by zacharlie** [comment] 2020-08-29 22:54
I just experienced this issue on windows after following the default instructions at https://superset.incubator.apache.org/installation.html by cloning the repo and running ```docker-compose```, but with a different response.

In my case, introspection of the _superset_init_ image showed ```/usr/bin/env: ‘bash\r’: No such file or directory``` in the log.

I explicitly replaced windows line endings in ```docker/docker-init.sh``` and ```docker-compose.yaml```, which seemed to resolve the issue for me. I used Edit>>EOL Conversion>>Unix (LF) in Notepad++

Related to #9037 and #7336

**Comment by jgreene** [comment] 2020-09-02 19:00
I just experienced this issue on ubuntu 18.04 starting from scratch.  It looks like there's some kind of pyarrow dependency conflict in superset-init

**Comment by devinrkeane** [comment] 2020-09-02 20:12
Hi all, I successfully installed superset two weeks ago on ubuntu 18.04.  I'm now running into this admin user/pw issue on subsequent installs from the docker-compose method, on multiple local machines -  Windows 10 and ubuntu 16.04 and 18.04 all running python 3.6 or 3.7.  I get this error during the build:

![superset-build-fail](https://user-images.githubusercontent.com/20322761/92031475-a7f3a180-ed36-11ea-80c8-62ed0174572d.png)

You can get to the login step but then the same error occurs. I've tried this on 4 different local machines today, two with the same specs as I have with the build that worked two weeks ago. 

Also, it appears the reference `requirements-local.txt` file in `Dockerfile-dev` should be named `requirements.txt`, based on the requirements folder.

**Comment by craig-rueda** [comment] 2020-09-03 03:18
I just pushed a fix for this into master. Please pull the latest and try one more time.

**Comment by devinrkeane** [comment] 2020-09-03 19:58
Thanks for the quick response!  This fixed for Ubuntu but still getting the Invalid login for windows after clean install.  Perhaps a different issue.

**Comment by Imperious2000** [comment] 2020-09-14 22:19
This is still a thing, updated to the latest version, same error message Invalid log in. Please try again.
, docs still mention admin: admin for username and password. Did clear all containers, images, volumes, built it again, and still the same message.

**Comment by mirwaisx** [comment] 2020-09-15 15:08
I have similar problem with the helm chart in K8s. One way to create user/or change password, is to log into the container and create admin user:
```
# Create an admin user (you will be prompted to set a username, first and last name before setting a password)
$ export FLASK_APP=superset
flask fab create-admin
```
Of course this is approach is not optimal as you have to do it manually and most importatntly after your container is recreated the user is also lost if not you are running the container in a stateless manner. The right way is to fix it in helm chart.

**Comment by chance2021** [comment] 2021-03-11 17:30
Hi, looks like the issue is fixed in **master** branch. Please git checkout master and re-build again. You should be able to login as admin/admin. Thanks

**Comment by eduardev** [comment] 2022-07-07 14:42
It's 2022 and:

- bug still exists
- issue still closed

¯\_(ツ)_/¯

**Comment by mkhudia** [comment] 2022-07-15 10:19
It's half past 2022 and: 

- Documented username and password `admin` `admin` don't work
- Even though superset gets set up locally but is unable to log in doesn't allow further developing on this. 
- the issue is still closed

**Comment by craig-rueda** [comment] 2022-07-15 17:30
Hey guys, I just tried these steps:

1. pull latest `master`
2. cd into repo
3. run `docker compose up`
4. wait...
5. Login to `http://localhost:8080` using `admin/admin`
6. SUCESS :) 

What steps / output are you seeing?

**Comment by mkhudia** [comment] 2022-07-16 03:33
@craig-rueda thanks for the swift reply. sharing the steps I am trying on my machine. 

- docker pull apache/superset:latest
- docker run -it -p 8088:8088 --name oli-superset <image-id> 
- navigate to http://localhost:8088 for superset login
- trying to login with username: admin password: admin
- Invalid login

**Comment by craig-rueda** [comment] 2022-07-18 16:08
Ah, steps are different :).

Pls try the ones I outlined. We don't ship any default creds with the base image. The docker-compose stack includes an "init" container that does a bunch of setup (including the creation of the `admin` user)

**Comment by mpvoss** [comment] 2023-07-27 17:33
Hello @craig-rueda , I think a recent merge created multiple heads for alembic, a head merge might be needed. Below is output from the init container after following your steps above. Should I open a new issue for this?


```Skipping local overrides
Unknown Operation!!!

######################################################################


Init Step 1/4 [Starting] -- Applying DB migrations


######################################################################

logging was configured successfully
2023-07-27 17:07:24,421:INFO:superset.utils.logging_configurator:logging was configured successfully
2023-07-27 17:07:24,425:INFO:root:Configured event logger of type <class 'superset.utils.log.DBEventLogger'>
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
ERROR [flask_migrate] Error: Multiple head revisions are present for given argument 'head'; please specify a specific target revision, '<branchname>@head' to narrow to a specific head, or 'heads' for all heads
Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
```

**Comment by bparts** [comment] 2023-08-14 14:26
This is actually embarassing, first of all provided installation on the official doc requires constant package name corrections, then I get this for no reason doing exactly as described on official stable Debian OS.
Is it a lib some school kid wrote, or it is actually a world known and used open source project... Feels more like first now.

**Comment by lucasrueda** [comment] 2023-08-29 04:48
Workaround: **Run steps described in [docker-init.sh](https://github.com/apache/superset/blob/72150ebadf1b76d2362969e9b4fad97f9f815ac9/docker/docker-init.sh#L40)**
Resume without loading tests:
```bash
ADMIN_PASSWORD="admin"
superset db upgrade
superset fab create-admin \
              --username admin \
              --firstname Superset \
              --lastname Admin \
              --email admin@superset.com \
              --password $ADMIN_PASSWORD
superset init
superset load_examples --force
```

**Comment by KonstantinOsipov** [comment] 2023-09-01 03:47
> Hey guys, I just tried these steps:
> 
> 1. pull latest `master`
> 2. cd into repo
> 3. run `docker compose up`
> 4. wait...
> 5. Login to `http://localhost:8080` using `admin/admin`
> 6. SUCESS :)
> 
> What steps / output are you seeing?

What VPS configuration will be sufficient to run Superset?

**Comment by yurishkuro** [comment] 2023-09-22 04:56
I was able to bypass the invalid credentials error by running `docker-compose run superset-init`, which seems to initialize the account. But that script fails with a different error in the end, and the frontend goes from the login page to a broken /welcome page. I'm giving up at this point.

**Comment by Willie-The-Lord** [comment] 2023-10-26 18:03
> Please nuke your images and volumes:
> 
> ```
> # Nukes containers:
> docker rm -f $(docker ps -aq | awk '{print $1}')
> 
> # Nukes images:
> docker rmi -f $(docker images | awk '{print $3}') 
> 
> # Nukes volumes:
> docker-compose down -v
> 
> # Re-Builds docker-compose:
> docker-compose build
> 
> # Stand everything back up:
> docker-compose up
> ```
> 
> Hope that helps!

I encountered the issue during the initial setup. After deleting the containers, images, and volumes, everything started working as expected.

**Comment by Captain404** [comment] 2024-01-10 15:08
What a useless app...all that effort to install and the default creds dont work. I tried a all the methods here but still no go. Also giving up and will maybe come back when it actually works.

**Comment by DutchyOven** [comment] 2024-02-22 02:23
> Please nuke your images and volumes:
> 
> ```
> # Nukes containers:
> docker rm -f $(docker ps -aq | awk '{print $1}')
> 
> # Nukes images:
> docker rmi -f $(docker images | awk '{print $3}') 
> 
> # Nukes volumes:
> docker-compose down -v
> 
> # Re-Builds docker-compose:
> docker-compose build
> 
> # Stand everything back up:
> docker-compose up
> ```
> 
> Hope that helps!

This is my fault but WARNING! In case you are newish to docker or just not used to these kinds of commands these commands will nuke all your containers and images, not just superset. Just erased all containers running on my server, not fun.

**Comment by aibunny** [comment] 2024-02-29 12:39
Also facing similar issue my instance was working but now I used the same image to build a separate instance and I can't log in @betodealmeida , Kindly help same issue as above on superset 3.1.1 and 3.1.0

**Comment by Carmageddon** [comment] 2024-04-17 21:24
This issue should be reopened, I've just run into the same issue with the latest Docker installed on Mac M2.
This is the first time using Superset, I will try removing related images etc, but I have to be careful I have other stuff including mounted volumes that i need to keep running, specifically Clickhouse right now with test data that I've loaded.

**Comment by mistercrunch** [comment] 2024-04-17 22:34
> I've just run into the same issue with the latest Docker installed on Mac

@Carmageddon how did you install? `docker-compose` is best for development or tes-driving, and will create a default admin/admin account.

**Comment by Neelam-Ranjan** [comment] 2024-08-21 00:09
I am still facing the issue - after creating flask fab user the browser goes in 'Internal server error' !!!!

**Comment by mistercrunch** [comment] 2024-08-21 00:33
>  after creating flask fab user the browser goes in 'Internal server error' !!!!

Seems like a different issue, any logs server side?

**Comment by Neelam-Ranjan** [comment] 2024-08-21 00:48
I am running Superset in Kubernetes and when I am trying to enter the default login details it says 'Invalid login try again' so I tried above suggestion - https://github.com/apache/superset/issues/10149#issuecomment-692779244 and got the 'Internal server 500' !!

**Comment by jamshidhashimi** [comment] 2024-10-10 22:28
The following worked for me.

First, I ran this:
```
sudo docker compose --file docker-compose-image-tag.yml exec superset superset fab create-admin \
    --username admin \
    --firstname Superset \
    --lastname Admin \
    --email admin@example.com \
    --password admin
```

afterwards ran this:
`sudo docker compose --file docker-compose-image-tag.yml exec superset superset db upgrade`

**Comment by mpvoss** [comment] 2024-12-04 20:55
@smfritzii I'm not sure if you're trying to run the latest development codebase, but I found that using an official release resolved the issue for me. Maybe there's a few different ways the default login can be broken by recent changes, but the official releases have been stabilized whereas the development branches are less stable.

https://superset.apache.org/docs/installation/docker-compose/#option-3---boot-up-an-official-release

**Comment by smfritzii** [comment] 2024-12-06 19:06
@mpvoss Interesting. I'm following the quickstart guide, which tells me that simply cloning this repo gets the "latest official release". Can I suggest modifying the quickstart guide to include finding / specifying an actual release?

![image](https://github.com/user-attachments/assets/97c52322-2a76-4337-b156-24fb40b2a45e)

**Comment by mistercrunch** [comment] 2024-12-07 01:14
the "Start the latest official release of Superset" instructions point to the `docker-compose-image-tag.yml` which should point to the latest release, currently `4.1.1`. Let me double check and leave a trace here:
- if no `TAG` env var is specified, we point to `latest-dev` image tag on docker hub [relevant line](https://github.com/apache/superset/blob/master/docker-compose-image-tag.yml#L24)
- this is [the latest-dev](https://hub.docker.com/layers/apache/superset/latest-dev/images/sha256-d2aa511163d0c3ff21ddd33ab85a089625c36a1f4c3fe12b279a3459c98a40e2?context=explore) image on docker-hub, pushed 18 days ago which looks about right, lines up with the 4.1.1 release from 2 weeks ago
- all docker-compose are supposed to execute [this script](https://github.com/apache/superset/blob/master/docker/docker-init.sh#L59-L64), which should create the `admin` user, you shouldn't have to do the incantations specified in comments above, at least not if you're using `docker-compose`
- tested `docker-compose -f docker-compose-image-tag.yml up` locally, seems to work just fine

If you have history of running different versions and/or doing development you may want to try nuking the postgres db to start from a clean slate: https://superset.apache.org/docs/contributing/development/#nuking-the-postgres-database

There's also other potential issue if you're not vanilla and for instance have setup your own `pythonpath`/config file or if you have ENV VARs defined that can affect the docker-compose behavior, for instance you'll see people that have set up env vars to point the database to a local instance over the docker-provided one in their `.bash_profile` and that throws off the setup.

**Comment by webbsledge** [comment] 2024-12-10 22:13
It seems there is a difference in behavior in initializing with the two commands:

`docker compose -f docker-compose-image-tag.yml up`

`docker compose -f docker-compose.yml up`

I haven't dug into the docker compose files, but the former works for me (on Mac) while the latter does not.

**Comment by muthubuntu** [comment] 2025-01-06 17:36
This error seems to solve itself if the container is allowed to fully build - if you try to log in before the build is finished, you end up with the error described here. But there is no error if you - as brilliantly suggested here - *wait* for the process to finish then log in. Just because the Superset login page is showing, doesn't mean the container is done building. I'm using Linux Mint with docker compose (not docker-compose)

**Comment by pavelkryl** [comment] 2025-01-28 19:56
This is driving me crazy. Have tried to install superset many times over over again - because I could not sign in with `admin`, `admin` even after launching command to change admin's password. Then I gave up with version 4.1.1 and tried to use 3.1.3 - and voila it works! (waiting for initialization to complete did not help) Spent 4 hours with this today.

Must be something wrong in version 4.1.1 - [here is](https://github.com/pavelkryl/superset-fail/blob/main/apache-superset.tgz) layout/directory structure where you can easily reproduce. Once you verify that it does NOT work (with image version 4.1.1), cleanup the persistent directories, change the image version to 3.1.3 and boot again.

**Comment by AleksB27** [comment] 2025-02-10 22:02
The following steps works for me (Win) - big thanks to @lucasrueda 
1. pull image `docker pull apache/superset`
2. generate a key `openssl rand -base64 42`
3. create a file `superset_config.py` with a key - for example in `c:/temp/`. It should look like this `SECRET_KEY = "CODE"`
4. run docker `docker run -p 8088:8088 --name superset -v c:/temp/superset_config.py:/app/pythonpath/superset_config.py apache/superset:latest`
5. it should be WAIT here, but i don't think it might be nessesarry 
6. run `docker exec -it superset superset db upgrade`
7. run `docker exec -it superset superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@example.com --password admin`
8. run `docker exec -it superset superset init`
9. open `http://localhost:8088/` - and you will see a dashboard.
