### ISSUE TITLE
[explore]View Samples does not work in Table viz 

### ISSUE THREAD

**Issue by junlincc** [apache/incubator-superset#11959] opened 2020-12-08 07:31 UTC
![ezgif-7-65388df35972](https://user-images.githubusercontent.com/67837651/101453197-cd6aeb00-38e3-11eb-919e-d818e2826eb6.gif)

this is not a regression introduced by any recent PRs. 
see gif, View Samples tab should show sample data of the underlying dataset in any data visualizations

**Comment by mayurnewase** [comment] 2020-12-16 04:47
@junlincc is this fixed in latest master?
I couldn't reproduce it.

**Comment by villebro** [comment] 2020-12-16 06:04
This should be fixed by #12055, so closing this for now

**Closed by villebro** 2020-12-16 06:04 UTC
Labels: #bug, .explore, flexiana
