### ISSUE TITLE
BoxPlot - multiple issues

### ISSUE THREAD

**Issue by nkconnor** [apache/incubator-superset#2222] opened 2017-02-22 21:32 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.4

### Expected results
Box plot displays using provided options.

### Actual results
Box plot throws KeyError on query for group by terms (1 or many)

### Steps to reproduce
Add a datasource
```
SELECT *,
        ROUND(RAND(1), 2) AS `measurement` 
FROM (
    SELECT
        NOW()-INTERVAL 1 HOUR AS `date`
    ) t1
    CROSS JOIN (
        SELECT "US" AS `attribute_1` UNION SELECT "CA" UNION SELECT "DE" UNION SELECT "AU"
    ) t2
     CROSS JOIN (
        SELECT "M" AS `attribute_2` UNION SELECT "F" UNION SELECT "C" UNION SELECT "N\A" 
    ) t3
;
```

1. Enter visualization for that data source
2. Select Box Plot
3. Add `measurement` to metrics; `attribute_1`, `attribute_2`, together or alone as group by terms
4. Hit Query

Stack trace

```
2017-02-22 16:27:06,176:ERROR:root:u'attribute_1'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/superset/views.py", line 1406, in explore_json
    payload = viz_obj.get_payload()
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 360, in get_payload
    data = self.get_data()
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 885, in get_data
    df = self.get_df()
  File "/usr/local/lib/python2.7/dist-packages/superset/viz.py", line 858, in get_df
    df = df.groupby(form_data.get('groupby')).agg(aggregate)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3778, in groupby
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby.py", line 1427, in groupby
    return klass(obj, by, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby.py", line 354, in __init__
    mutated=self.mutated)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/groupby.py", line 2383, in _get_grouper
    in_axis, name, gpr = True, gpr, obj[gpr]
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 1997, in __getitem__
    return self._getitem_column(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2004, in _getitem_column
    return self._get_item_cache(key)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 1350, in _get_item_cache
    values = self._data.get(item)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3290, in get
    loc = self.items.get_loc(item)
  File "/usr/local/lib/python2.7/dist-packages/pandas/indexes/base.py", line 1947, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 137, in pandas.index.IndexEngine.get_loc (pandas/index.c:4154)
  File "pandas/index.pyx", line 159, in pandas.index.IndexEngine.get_loc (pandas/index.c:4018)
  File "pandas/hashtable.pyx", line 675, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12368)
  File "pandas/hashtable.pyx", line 683, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12322)
KeyError: u'attribute_1'
```

Additionally the Box Plot graph type is requiring a date. This shouldn't be necessary.

**Comment by prcastro** [comment] 2018-01-15 22:28
I'm having the same issue. Box plot is requiring a datetime column (which shouldn't be necessary) and I can't plot what I need

**Comment by AxelMathei** [comment] 2018-05-29 09:05
The datetime issue was already mentioned in https://github.com/apache/incubator-superset/issues/786 and the commit https://github.com/apache/incubator-superset/commit/9cdd289081b9e5faf9f8136151502398f6c01369 fixed it but the is_timeseries boolean is again at True.

**Comment by jpambrun** [comment] 2018-12-04 22:01
Any way to move that forward? I am new to superset and I want to create a boxtplot of patient weight with respect to sex.

I am forced to aggregate weight and the query looks like :
``` slq
SELECT patientsex AS patientsex,
       studydate AS __timestamp,
       AVG(patientweight) AS "AVG(patientweight)"
FROM images
GROUP BY patientsex,
         studydate
ORDER BY "AVG(patientweight)" DESC
```

the `studydate AS __timestamp` and `GROUP BY studydate` is not something I want and is not something I can change from the UI. I assume this is caused by the `is_timeseries=False` flag?

I don't quite understand the use-case for a timeseries-based boxplots; is this really the intended behaviour?

**Comment by muraiki** [comment] 2019-04-11 23:00
Please don't close this issue, as it prevents boxplots from being used.

**Closed** 2020-10-17 08:02 UTC
Labels: .pinned, .vis
