### ISSUE TITLE
Problem installing Superset from master branch

### ISSUE THREAD

**Issue by syazwan0913** [apache/incubator-superset#10055] opened 2020-06-15 14:04 UTC
### Expected results

Can run Superset from `master` branch in first time installation

### Actual results

Problem on npm

#### Screenshots

Terminal:
![Capture](https://user-images.githubusercontent.com/28984703/84666627-e8235f00-af53-11ea-9403-99330582b332.PNG)

Browser:
![Capture](https://user-images.githubusercontent.com/28984703/84666506-bd390b00-af53-11ea-973e-e1f89ebbb345.PNG)

#### How to reproduce the bug

1. Run `docker-compose up` to start all the containers

### Environment

- superset version: `master`
- python version: `3.6.9`
- node.js version: `10-jessie`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by willbarrett** [comment] 2020-06-24 22:41
@syazwan0913 would you mind providing an expanded error trace? It looks like your `superset-node` container is not successfully building assets. Please examine the output from that container and let us know what you find.

**Comment by syazwan0913** [comment] 2020-06-25 05:03
@willbarrett After I complete remove all superset docker images and volumes, I successfully installed it

**Comment by willbarrett** [comment] 2020-06-25 13:16
OK, it appears that you are running into a dependency conflict on SQLAlchemy. I just attempted to rebuild our Docker container locally and ran into the same issue. I'll work on a fix today.

**Comment by syazwan0913** [comment] 2020-06-26 00:51
Yes I had to temporary downgrade `sqlalchemy-utils` version in order to make the installation working

**Comment by syazwan0913** [comment] 2020-07-05 09:26
@willbarrett Is it fixed already?

**Comment by willbarrett** [comment] 2020-07-06 19:56
@syazwan0913 we discovered that the dependency issue was due to an unnamed Docker volume that carried the older dependency forward. We've run this to blow away our docker volumes locally and resolve the issue:

**Comment by syazwan0913** [comment] 2020-07-09 05:02
@willbarrett Okay I will try it out. Thanks

**Comment by willbarrett** [comment] 2020-08-20 20:13
Closing as this issue is no longer reproducible on master.

**Closed by willbarrett** 2020-08-20 20:13 UTC
Labels: #bug
