### ISSUE TITLE
[Filter Box] TypeError: Cannot read property 'region' of undefined

### ISSUE THREAD

**Issue by vylc** [apache/incubator-superset#4433] opened 2018-02-15 01:03 UTC
Postgres table with varchar(256) type throws this error when placed in the filter by box:
http://superset-prod.lyft.net/r/99
<img width="877" alt="screen shot 2018-02-14 at 5 00 50 pm" src="https://user-images.githubusercontent.com/33429480/36283196-91f14484-1258-11e8-9425-7de2b1724bea.png">

Make sure these boxes are checked before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if any
- [ x] I have reproduced the issue with at least the latest released version of superset
- [ x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.23.0rc2

**Comment by timifasubaa** [comment] 2018-02-15 01:10
Can you share a picture of the error or the stack trace?

**Comment by raffas** [comment] 2018-02-15 08:39
Please specify superset version. 

This maybe is an error that is resolved with the latest commits. I've close yesterday a similar bug #4391 and was caused by the new cache system.

Also check that the query returns data for the time range you have selected

**Comment by hughhhh** [comment] 2018-02-19 03:32
Can we confirm this @vylc?
It looks like its working in our prod. I just upgrade things let me know

**Comment by mistercrunch** [comment] 2018-02-19 17:59
Confirmed fixed

**Closed by mistercrunch** 2018-02-19 17:59 UTC
