### ISSUE TITLE
https://superset.apache.org/ - website not scrolling

### ISSUE THREAD

**Issue by arunpune** [apache/incubator-superset#11316] opened 2020-10-17 09:19 UTC
Hello
https://superset.apache.org/ is having problems. On the right side of the pages there are scroll bars.  I am not able to scroll the Text down.

**Comment by zhaoyongjie** [comment] 2020-10-17 14:04
@arunpune I use the latest Firefox and Chrome on OSX, the websites are all normal.

which browser do you use?

**Comment by arunpune** [comment] 2020-10-19 09:13
@zhaoyongjie i have the latest Google Chrome Broswer.
Google Chrome is up to date
Version 86.0.4240.75 (Official Build) (64-bit)
I am not able to scroll it up and down. 

https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

check this link given above
It does not work on Fire fox Mozilla also

**Comment by junlincc** [comment] 2020-12-01 23:27
hey @arunpune, sorry we are not able to reproduce it in chrome or mozilla, and we have not seen any other similar reports. im closing this issue for now. 
![ezgif-2-01dac055c022](https://user-images.githubusercontent.com/67837651/100808801-ab580100-33e9-11eb-9c29-e127c33fd90d.gif)

**Closed by junlincc** 2020-12-01 23:27 UTC
Labels: #bug

**Comment by Adrian08011990** [comment] 2022-02-23 14:10
I have the same behavior - tried Firefox, Chro
![superset](https://user-images.githubusercontent.com/22958963/155335794-fd47606e-f379-47d1-bf10-1fa96957e03d.PNG)
me, Opera.
Windows 10 OS. 
All browsers up-to-date
Scroll bar doesn't want to move more that what can be seen in the snip attached.
Tried re-dimensioning my browser, clearing cache, nothing works

**Comment by villebro** [comment] 2022-02-23 14:14
@Adrian08011990 - thanks, but this appears to be a (closed) duplicate of #18868 .
