### ISSUE TITLE
Optimizing Superset rendering

### ISSUE THREAD

**Issue by vibinsv09** [apache/incubator-superset#4732] opened 2018-04-02 03:43 UTC
Current size of dashboard.entry.js is aroung 7+ MB which causes slight sluggishness in rendering.
Are there any optimizations that I can do to reduce its size and improve overall rendering speed?

**Comment by mistercrunch** [comment] 2018-04-02 04:11
Duplicate of https://github.com/apache/incubator-superset/issues/4705

**Closed by mistercrunch** 2018-04-02 04:11 UTC
