### ISSUE TITLE
(psycopg2.OperationalError) FATAL: database "public" does not exist

### ISSUE THREAD

**Issue by witwall** [apache/incubator-superset#1873] opened 2016-12-21 03:52 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.15.0

### Expected results
Show the result of SQL

### Actual results

```
(psycopg2.OperationalError) FATAL: database "public" does not exist

```

### Steps to reproduce
access PostgreSQL through SQL Lab, 

![superset000](https://cloud.githubusercontent.com/assets/3222056/21376857/5e28eb56-c773-11e6-86ff-0c2efe8f40ac.png)

**Comment by xrmx** [comment] 2016-12-21 10:23
Does it work if you don't specify the schema?

**Comment by witwall** [comment] 2016-12-21 12:50
@xrmx does not work, but preview works sometime

**Comment by mistercrunch** [comment] 2016-12-21 17:39
Does it work if you SELECT ... FROM activity instead of public.activity?

**Comment by witwall** [comment] 2016-12-22 02:17
it works no matter 
```
SELECT *
FROM public.vintage LIMIT 100
```
or 
```
SELECT *
FROM vintage LIMIT 100
```
just if I did not select any schema from let panel.

![superset001](https://cloud.githubusercontent.com/assets/3222056/21412969/18c0380a-c82f-11e6-8780-bf5bad980e7b.png)

**Comment by dvayasdi** [comment] 2017-01-05 00:18
I can confirm that I'm facing the same issue. If I choose the schema explicitly in the left pane and try to query a table with either

`SELECT * FROM <schema_name>.<table_name>`
or
`SELECT * FROM <table_name>`
I get the error 
`(psycopg2.OperationalError) FATAL: database <schema_name> does not exist`

If I don't choose the schema name from the drop down and try to do 
`SELECT * FROM <schema_name>.<table_name>`, everything works fine.

**Comment by Pixelartist** [comment] 2017-02-10 16:41
Hello,

+1 - I am having the same issue, running superset in docker.

**Comment by mistercrunch** [comment] 2017-02-10 17:13
Is there a full stacktrace from the server logs?

**Comment by mistercrunch** [comment] 2017-02-10 17:17
Most likely the issue is around confusion between the `database` and `schema` "namespacing" in Postgres. Databases have different semantics in that area on how they name these logical groups (database, schema, owner) and how many levels of them they have, and SQLAlchemy takes a bit of a common denominator approach.

**Comment by mistercrunch** [comment] 2017-02-10 17:18
Since we don't use Postgres at Airbnb I'd like for someone to step in and help fix this.

**Comment by huksley** [comment] 2017-02-18 11:41
I have similar problem. Can`t deselect schema.

**Comment by colmsnowplow** [comment] 2017-02-28 09:48
+1 here, getting error regardless of the schema selected and format of the FROM statement.

**Comment by sungjuly** [comment] 2017-03-01 22:09
It's same/duplicated issue with https://github.com/airbnb/superset/issues/1558, and my PR was merged the last couple of days. You can use that feature in the next release.
* https://github.com/airbnb/superset/pull/1789

**Comment by mistercrunch** [comment] 2017-03-01 22:30
0.17 is out!

**Comment by gustavodemari** [comment] 2017-04-06 22:23
The problem continues on 0.17.3

**Comment by mistercrunch** [comment] 2018-04-23 15:30
Notice: this issue has been closed because it has been inactive for 381 days. Feel free to comment and request for this issue to be reopened.

**Closed by mistercrunch** 2018-04-23 15:30 UTC
Labels: bug_cant_reproduce, help wanted, postgres
