### ISSUE TITLE
SQL Lab: Search table name with schema will cause page to crash

### ISSUE THREAD

**Issue by zuzana-vej** [apache/incubator-superset#11070] opened 2020-09-25 22:40 UTC
When you paste table name without selection a schema, the SQL Lab page crashes. This has been noticed as a regression - which would have likely been introduced in the last week. 

### Actual results
SQL Lab page crashes

#### Screenshots
![sqllab-error](https://user-images.githubusercontent.com/61221714/94321632-0cc0a700-ff45-11ea-865c-9141a374ed08.gif)

#### How to reproduce the bug

1. Switch to other schema
2. Switch back to the schema you want
3. in the “See table schema” select box type: “foo” and hit enter
4. Wait and see the page crash

### Environment
Latest master version

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment] 2020-09-27 07:03
hi, @zuzana-vej , which version do you use or give me the SHA string, like flowing the image.
<img width="351" alt="image" src="https://user-images.githubusercontent.com/2016594/94358252-4377f800-00d2-11eb-9535-ca96d3ed4784.png">

by the way,  the latest master branch. the SQLLab can not select table if you do not choose schema.

**Comment by graceguo-supercat** [comment] 2020-09-28 19:41
It's still reproduce-able the latest master branch. after load sql lab, type `abc` in schema input box, then type `abc` in table input box.

**Comment by willbarrett** [comment] 2020-09-29 22:17
@graceguo-supercat @zuzana-vej  I'm unable to replicate this - can you share information on browser used and anything else that might help me find the issue? For me, the "table" dropdown is not enabled until I select a valid schema, even when I put a search string into the schema search field.

**Comment by zuzana-vej** [comment] 2020-09-29 22:30
@willbarrett  it's possible there was a fix which was merged into master the last 6 days (we are currently 6 days behind). We will check tomorrow and let you know tomorrow if we still see and if yes, more details on how to reproduce it.

**Comment by willbarrett** [comment] 2020-10-19 15:56
Closing as unable to reproduce.

**Closed by willbarrett** 2020-10-19 15:56 UTC
Labels: #bug, sqllab

**Comment by zuzana-vej** [comment] 2020-10-19 17:00
Agreed, it looks fixed (also couldn't repro it anymore).
