### ISSUE TITLE
All tutorial images are down

### ISSUE THREAD

**Issue by karen-pal** [apache/incubator-superset#9584] opened 2020-04-19 16:22 UTC
Adding to  #9581, In the [official tutorial page](https://superset.apache.org/tutorials.html), the images illustrating each step are down. That happens for all images in the tutorial as far as I tested. They are either down or aren't a link.

#### Screenshots
a link to an image
![imagen](https://user-images.githubusercontent.com/55008020/79693147-66f36880-823f-11ea-865a-adc290931227.png)

when opening the image 
![imagen](https://user-images.githubusercontent.com/55008020/79693232-cd788680-823f-11ea-8c12-9f06d345c307.png)

Some are plain text instead of links to images
![imagen](https://user-images.githubusercontent.com/55008020/79693209-ade15e00-823f-11ea-856c-8b167fccd8d7.png)

**Comment by villebro** [comment] 2020-04-19 18:56
Thanks for reporting @karen-pal , I will investigate asap. This seems to be a regression from the deployment of the docs for `0.36.0`.

**Comment by villebro** [comment] 2020-04-20 08:29
Docs should now work again.

**Comment by karen-pal** [comment] 2020-04-20 18:40
up and working, thanks!! Should I close the issue?

**Comment by villebro** [comment] 2020-04-21 04:11
Let's leave this open and let the fix PR close it when it merges.

**Closed** 2020-04-22 16:11 UTC
Labels: #bug
