### ISSUE TITLE
default login/password not known after bringing up the Docker container

### ISSUE THREAD

**Issue by wtian** [apache/incubator-superset#7336] opened 2019-04-20 08:22 UTC
### Motivation

After successfully installing the Docker image, bringing up the container and pointing my browser to http://localhost:8088, I am asked to login. But I have no idea what the default login/password combo is.

### Proposed Change

Make it clear what the default login/password is, either by mentioning it in the install guide or using greyed-out placeholder in the input fields.

**Comment by maksimu** [comment] 2019-06-02 04:53
And what is the default username and password?

**Comment by dancrew32** [comment] 2019-07-11 05:44
So I missed this during install as well, but it prompts you to create a username, first, last, email, and password at this phase:
~/src/superset/contrib/docker$ docker-compose run --rm superset ./docker-init.sh
Starting superset_postgres_1 ... 
Starting superset_redis_1 ... done
+ '[' 1 -ne 0 ']'
+ exec ./docker-init.sh
+ export FLASK_APP=superset:app
+ FLASK_APP=superset:app
+ flask fab create-admin
Username [admin]: 
```bash
Username [admin]: admin
User first name [admin]: admin
User last name [user]: admin
Email [admin@fab.org]: admin@fab.org
Password: 
Repeat for confirmation: 
```

you can try `docker exec -it superset_superset_1 bash` and run `./docker-init.sh` to trigger this same prompt:
https://github.com/apache/incubator-superset/blob/master/contrib/docker/docker-init.sh#L22

**Comment by ManuelLevi** [comment] 2019-12-18 17:35
Try `admin`:`admin`. Couldn't find it on the documentation, to find them, I had to investigate and find them in the `docker-init.sh` script.
This should be in the documentation.

**Comment by sibblegp** [comment] 2020-02-07 20:57
This should absolutely be documented. It's like hitting a brick wall.

**Comment by daniel-zahariev** [comment] 2020-02-26 17:24
I used `docker-compose exec superset bash /app/docker-init.sh`

**Comment by KuriaMaingi** [comment] 2020-03-06 18:11
> I used `docker-compose exec superset bash /app/docker-init.sh`

This worked for me but with a slight modification directly to the superset app:
`docker-compose exec incubator-superset_superset_1 bash /app/docker-init.sh`

**Comment by willbarrett** [comment] 2020-03-09 16:51
Thanks all for bringing this to the community's attention. I've opened a PR to update our docs.

**Comment by willbarrett** [comment] 2020-03-10 15:22
Documentation PR has been merged, the default username/password will appear on https://superset.incubator.apache.org/installation.html on the next update.

**Closed** 2020-03-10 15:25 UTC

**Comment by Zonalds** [comment] 2020-04-22 03:25
I am running the image on GKE but when I try the admin and admin for the username and password it doesn't work. I suppose the admin was not created. Any idea how to create the admin? 

I read a few posts that suggest I need to navigate to contrib/docker to create the admin. Any idea how to navigate to contrib/docker on GKE?

**Comment by jonahbenton** [comment] 2020-06-12 10:19
As of early June, for GKE, the stable channel helm chart for superset defaults to production-mode, which does not create an initial admin user. 

I am working through getting the chart to start with development-mode, which does, but the chart templates have some problems, including hard-coding the production port. Will post again when I get them working.

**Comment by mirwaisx** [comment] 2020-09-15 15:13
> As of early June, for GKE, the stable channel helm chart for superset defaults to production-mode, which does not create an initial admin user.
> 
> I am working through getting the chart to start with development-mode, which does, but the chart templates have some problems, including hard-coding the production port. Will post again when I get them working.

yes I can confirm, for me just for testing purpose I created the user manually as mentioned here [#10149 ](https://github.com/apache/incubator-superset/issues/10149#issuecomment-692779244)

**Comment by tomrod** [comment] 2020-09-23 01:56
I followed the instructions here with fresh install and git pull and `admin:admin` does not work:

https://superset.incubator.apache.org/docs/installation/installing-superset-using-docker-compose

**Comment by nytai** [comment] 2020-09-23 02:04
@tomrod do you have logs for the `superset_init` container? That container should run a script that creates the admin user. Either that script hasn't finished running or it has errored out.

**Comment by tomrod** [comment] 2020-09-23 02:15
Happy to check. Apologies for being a bit a newb, how do I grab that?

**Comment by nytai** [comment] 2020-09-23 02:19
https://docs.docker.com/engine/reference/commandline/logs/

**Comment by tomrod** [comment] 2020-09-23 02:34
```PS D:\Docker\incubator-superset> docker logs e9417a5c1755
/usr/bin/env: ‘bash\r’: No such file or directory
/usr/bin/env: ‘bash\r’: No such file or directory

**Comment by nytai** [comment] 2020-09-23 02:54
@tomrod are you running this on a windows machine by chance?

**Comment by tomrod** [comment] 2020-09-23 02:55
Giving it a go with docker+wsl

**Comment by tomrod** [comment] 2020-09-23 03:10
That said, why would installing on windows make `admin:admin` user account not be created?

**Comment by nytai** [comment] 2020-09-23 03:11
because the script that creates the admin user is erroring out due to the way windows formats files.

**Comment by nytai** [comment] 2020-09-23 03:12
I'm surprised you even got the app stood up running on windows

**Comment by tomrod** [comment] 2020-09-23 03:19
Looks like the login issue was related to carriage returns -- fetching the repo via WSL and rebuilding fresh removed the login issue.

However, the app does not appear to be running after login, which is beyond scope of this issue :) 

![image](https://user-images.githubusercontent.com/1719700/93962997-aa3b9100-fd21-11ea-8419-94f499439ab2.png)

**Comment by nytai** [comment] 2020-09-23 03:31
@tomrod the app is running, the frontend hasn't finish building yet so you're getting this blank page. Give it a while longer and it should load up. The logs from `superset_node` should give you a clue as to the progress

**Comment by tomrod** [comment] 2020-09-23 04:09
Thanks! Will do. We're looking to evaluate this for our healthcare R&D
group -- visually looks nice, looking forward to evaluating.

**Comment by tomrod** [comment] 2020-09-23 04:30
Up and running on Windows 10 Home w/ Docker Desktop +WSL

**Comment by ShaileshAdhikari** [comment] 2020-10-19 15:49
> Looks like the login issue was related to carriage returns -- fetching the repo via WSL and rebuilding fresh removed the login issue.
> 
> However, the app does not appear to be running after login, which is beyond scope of this issue :) -- I'll give it a go in a VM instead
> 
> ![image](https://user-images.githubusercontent.com/1719700/93962997-aa3b9100-fd21-11ea-8419-94f499439ab2.png)



> Up and running on Windows 10 Home w/ Docker Desktop +WSL


Hello tomrod, I am having the same issue and using the same system Windows 10 Docker Desktop + WSL. I followed many fixes but nothing is working ! Can yo provide some insights, how do you make it work !

**Comment by tomrod** [comment] 2020-10-19 17:59
I pulled the repo using git in Debian Linux WSL instead of Windows. This
fixed the carriage return issues. I then let it run for several minutes
after docker said setup was done before attempting to log in. There may be
some background processes that should be logged.
