### ISSUE TITLE
[Welcome] confusing Saved Queries card

### ISSUE THREAD

**Issue by ktmud** [apache/incubator-superset#11659] opened 2020-11-11 20:29 UTC
## Screenshot

<img src="https://user-images.githubusercontent.com/335541/98860297-47f53780-2418-11eb-8562-07cdbe1aaf7a.png" width="600">

## Description

I don't think I understand the elements  of this card.

1. What is `Table 1`?
2. Timestamp seems missing for "Last run"
3. The position of "···” seems off.
4. The header is too heavy, kind of making the most important info--the query name (or label)---not visible enough, especially with cutoff. Maybe we should rid of "table" and "datasource name", and find ways to focus on these two user-inputed fields instead.
    <img src="https://user-images.githubusercontent.com/335541/98860920-41b38b00-2419-11eb-971b-4b9a44824aad.png" width="300">

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

**Comment by junlincc** [comment] 2020-11-11 22:01
on it, thanks for reporting.

**Comment by mihir174** [comment] 2020-11-11 22:20
<img width="457" alt="Group 12 (1)" src="https://user-images.githubusercontent.com/64227069/98870665-7713a500-2428-11eb-9cf7-dd71e071e6d4.png">

thanks for the quick feedback @ktmud ! this is what the cards are intended to look like^

1. the number under "tables" is the number of tables
2. good catch, the timestamp is supposed to appear right next to "last run"
3. that position is off probably due to the missing favorites button
4. the query name is meant to be heavier like in the above mockup. the name also it appears below the other info to be consistent with other cards like the dashboard and chart cards. for the label - i wasn't sure how important the labels were, so this is super helpful to know. i'll work to make that more prominent in the next round of designs :)

**Comment by junlincc** [comment] 2020-11-11 22:30
1. then there is a bug.. in my case should be 7 instead of 1....
4. @mihir174  i think @ktmud was referring to the save query modal in sql lab. the title and X are not aligned... and the buttons need to be reordered. 
<img width="307" alt="Screen Shot 2020-11-11 at 2 25 50 PM" src="https://user-images.githubusercontent.com/67837651/98871795-6401d480-242a-11eb-8ed1-758a833d0a8d.png">

**Comment by ktmud** [comment] 2020-11-12 00:12
"Label" is the query name, it's just we call it "label" in the save query form.

Another idea is to display a snippet of the query itself instead of the description. E.g.

<img src="https://user-images.githubusercontent.com/335541/98878510-0a080b80-2438-11eb-80de-56967ae324a4.png" width="400">

Also note that currently Superset doesn't support favoriting saved queries yet, which is probably why @pkdotson didn't add the favorite button in the first place. Whether we want to add support for favoriting them is another question, but before we do, we should probably disable the "Favorites" tab for now.

**Comment by mistercrunch** [comment] 2020-11-12 00:37
@ktmud +1 on SQL maybe even with aggressively small characters ~8px

**Comment by mistercrunch** [comment] 2020-11-12 00:37
Crazy idea: thumbnail + fisheye!

**Comment by junlincc** [comment] 2020-11-12 16:59
@ktmud getting rid of the table number since it's too confusing, adding snippet.

**Comment by mihir174** [comment] 2020-11-13 00:01
@ktmud that makes sense, and i like the idea of show code snippets in the cards, especially since it's difficult to fit them into list views. i built on the screenshot you provided and modified the layout to be more consistent with the dashboard and chart cards - 
<img width="457" alt="Group 32" src="https://user-images.githubusercontent.com/64227069/99011063-135cab00-2500-11eb-83e3-4b979118f9c9.png">

**Comment by mihir174** [comment] 2020-11-13 00:11
Here's what it could look like on the home page - 
<img width="1456" alt="Updated Query Cards@2x" src="https://user-images.githubusercontent.com/64227069/99011791-bc57d580-2501-11eb-9cec-7351ab75e898.png">

**Comment by ktmud** [comment] 2020-11-13 19:26
@mihir174 thanks for the updates! Any reason to give the query snippet a gray background? Currently it kind of blends too well with the page background.

I like the new icons for charts in the Recents section! Much more distinguishable than current icon.

Looking at this page more, I'd like to make a couple of more suggestions for your consideration: @junlincc @mistercrunch 

1. Should we move the Charts section above Saved Queries, or even Dashboards?
2. For Superset instances that do not have thumbnails enabled, maybe we could change the thumbnail cards to use the same style as the Recents cards.
3. The Recents cards uses "Last Edited: {absolute timestamp}" but the thumbnail cards says "Last modified {relative time}":
   1. Should we have some consistency here?
   2. Should the recently viewed cards use "Last viewed"?
3. In the Recents section, even with the icons, it's still a little hard to tell whether a card represents a dashboard or a chart. I wonder if we can change the whole section to be only about "Recently viewed", and use the tabs to filter by entity types.

**Comment by junlincc** [comment] 2020-11-13 20:19
> @mihir174 thanks for the updates! This looks good. Any reason to give the query snippet a gray background? Currently it kind of blends too well with the page background. Would also be curious to see how the card looks like when the title is very long.
> 
> I like the new icons for charts in the Recents section! Much more distinguishable than the current icons.
> 
> Looking at this page more, I'd like to make a couple of more suggestions for your consideration: @junlincc @mistercrunch
> 
> 1. Should we move the Charts section above Saved Queries, or even Dashboards?
> 2. For Superset instances that do not have thumbnails enabled, maybe we could change the thumbnail cards to use the same style as the Recents cards.
> 3. The Recents cards uses "Last Edited: {absolute timestamp}" but the thumbnail cards says "Last modified {relative time}":
>    
>    1. Should we have some consistency here?
>    2. Should the recently viewed cards use "Last viewed"?
> 4. In the Recents section, even with the icons, it's still a little hard to tell whether a card represents a dashboard or a chart. I wonder if we can change the whole section to be only about "Recently viewed", and use the tabs to filter by entity types.

1. +1 on moving charts above saved queries, but i know some companies are heavy users of SQL lab and they may want to prioritize saved queries info.
2. we can certainly consider it, given enable thumbnails is such a pain.... 
3. totally agree to keep the consistent. i voiced that before as well
4. need design input. @mihir174

**Comment by junlincc** [comment] 2020-11-13 23:01
> Would also be curious to see how the card looks like when the title is very long.
good one! 😆 @mihir174 please take that into consideration 

1. I personally like the idea of moving chart section above saved queries, but it really depends on the users. there are companies that rely heavily on SQL lab and not so much charting. ideally, we should allow user to decide the order. 
2. @nytai I believe Tai is working on the solution. but I agree we should provide that option on the welcome page. especially enabling thumbnail is such a pain...
3.  I'm not sure  "Last Edited" and "Last modified" are by designed..... but please at least keep cases consistent! 
4. the icons look pretty clear to me but we can certainly provide a different mockup to compare and run test on

**Comment by mihir174** [comment] 2020-11-17 00:56
@ktmud long titles are gonna be treated like the dashboard and chart cards - they will be truncated and the user will be able to see the whole title on hover 

here's a mockup:
<img width="668" alt="Slice 1" src="https://user-images.githubusercontent.com/64227069/99326176-a2353480-282c-11eb-8f69-0bef36156ca9.png">

and here's an example of dashboard cards with long titles:
![Frame 241](https://user-images.githubusercontent.com/64227069/99326189-ab260600-282c-11eb-9798-67393f1c2bad.jpg)

**Comment by junlincc** [comment] 2020-11-17 02:42
<img width="418" alt="Screen Shot 2020-11-13 at 5 52 52 PM" src="https://user-images.githubusercontent.com/67837651/99339034-3954b900-283a-11eb-800e-131b71e29999.png">

i understand that showing title is important to your users. if we don't truncate long title, then the card will look really overloaded and no longer serve their purpose as an information overview. @ktmud

**Comment by ktmud** [comment] 2020-11-17 04:54
What do you mean it doesn't serve its purpose?

**Comment by junlincc** [comment] 2020-11-17 05:48
> @ktmud long titles are gonna be treated like the dashboard and chart cards - they will be truncated and the user will be able to see the whole title on hover

@mihir174 @pkdotson I don't think _**see title on hover**_ is implemented on any cards, please make sure .........

**Comment by junlincc** [comment] 2020-11-17 06:05
> What do you mean it doesn't serve its purpose? I think they look kind of OK:
> 
> ![image](https://user-images.githubusercontent.com/335541/99349154-1f25d580-2850-11eb-8365-22606ab55976.png)

if you say that showing a veeeeeeeerrrrrrrrrrrryyyyyyyyyyyyyyyy long full title is what users are looking for, and that's why we should change the design, I may agree we should reconsider it! 
What you are suggesting here is that we MUST display the long title even though it could compromise the snippet content,,, and having different query card layouts looks OK...hm... I see what you mean, but I'm not entirely convinced. 
again, we should continue to have this discussion based on user feedback, nothing is set at this point. thank you always for brining up good points!🙏 @ktmud

**Comment by ktmud** [comment] 2020-11-17 07:33
I don't have a strong opinion on whether the title should be truncated here as it's less a data accuracy issue here than on dashboards and the titles are less likely to be very long or have similar prefixes anyway.

**Comment by ktmud** [comment] 2020-11-17 07:35
I think it's OK to just show an HTML title attribute. Tooltip might be a little too heavy in this case, especially if most titles don't truncate.

**Comment by rusackas** [comment] 2020-11-17 07:50
The real perk of the tooltip in my view is that it displays a bit faster than the html title. That makes it a little more discoverable to those with cursors, even if perhaps it's less accessible from an a11y standpoint. So... I guess it's kind of a tossup :)

**Comment by nytai** [comment] 2020-11-30 22:11
can we close this since ☝️ merged?

**Comment by junlincc** [comment] 2020-11-30 22:12
we will get rid of the Favorite tab in a separate PR in the hardening phase. closing this issue for now. 
<img width="598" alt="Screen Shot 2020-11-30 at 2 12 36 PM" src="https://user-images.githubusercontent.com/67837651/100671965-1df7ac80-3316-11eb-84b4-c28fa676a031.png">

**Comment by nytai** [comment] 2020-11-30 22:13
@rusackas since the truncation is being handled by css, I can't think of a way to only show a tooltip if there is truncation. I think adding a tooltip of every single title will make the whole page kind of jumpy.

**Closed by junlincc** 2020-11-30 22:12 UTC
Labels: cosmetic-issue

**Comment by nytai** [comment] 2020-11-30 22:15
ok, looks like all titles have tooltips now 😕

**Comment by rusackas** [comment] 2020-11-30 22:26
Correct.... my dream of an `:is-overflowed` selector still eludes me.

**Comment by junlincc** [comment] 2020-11-30 22:29
🥺 let's move on for now lol~

**Comment by rusackas** [comment] 2020-11-30 23:47
Oooh, [this looks promising](https://codesandbox.io/s/ant-design-conditional-tooltip-yuxx5?file=/src/TooltipParagraph.tsx:409-461)... for another PR.

**Comment by nytai** [comment] 2020-11-30 23:51
oh that's great, we can definitely use that in some of the listviews
