### ISSUE TITLE
Compile problem: gulp-sourcemaps: No matching version found for gulp-sourcemaps@1.7.0

### ISSUE THREAD

**Issue by luxward** [apache/incubator-superset#3152] opened 2017-07-18 06:38 UTC
### Version
- Superset 0.18.5
- npm node v6.10.0
- npm verb npm  v5.3.0

### Problem
executing script "./static/assets/js_build.sh" failed

### Log file
npm verb type version
npm verb stack gulp-sourcemaps: No matching version found for gulp-sourcemaps@1.7.0
npm verb stack     at pickManifest (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:61:11)
npm verb stack     at fetchPackument.then.packument (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:51:18)
npm verb stack     at tryCatcher (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm verb stack     at Promise._settlePromiseFromHandler (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
npm verb stack     at Promise._settlePromise (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
npm verb stack     at Promise._settlePromise0 (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
npm verb stack     at Promise._settlePromises (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
npm verb stack     at Async._drainQueue (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
npm verb stack     at Async._drainQueues (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
npm verb stack     at Immediate.Async.drainQueues (/home/liuxiangwei/.jumbo/opt/nodejs-bin/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
npm verb stack     at runCallback (timers.js:651:20)
npm verb stack     at tryOnImmediate (timers.js:624:5)
npm verb stack     at processImmediate [as _immediateCallback] (timers.js:596:5)
npm verb cwd /home/liuxiangwei/.jumbo/lib/python2.7/site-packages/superset-0.18.5-py2.7.egg/superset/static/assets
npm verb Linux 2.6.32_1-14-0-0

**Comment by xrmx** [comment] 2017-07-18 08:14
Duplicate of #3115, please close.

**Closed** 2017-07-18 09:17 UTC
