### ISSUE TITLE
Fresh install with Docker gives Error: No such command "load_examples".

### ISSUE THREAD

**Issue by ventouris** [apache/incubator-superset#6172] opened 2018-10-24 09:17 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
Superset 0.999.0dev

### Expected results
To finish the installation and let me open the browser at the following url http://localhost:8088

### Actual results
installation breaks with the error below

### Steps to reproduce

Do a fresh install with Docker in MacOs Mojave
```
git clone https://github.com/apache/incubator-superset/
cd incubator-superset
cp contrib/docker/{docker-build.sh,docker-compose.yml,docker-entrypoint.sh,docker-init.sh,Dockerfile} .
cp contrib/docker/superset_config.py superset/
bash -x docker-build.sh
docker-compose up -d
docker-compose exec superset bash
bash docker-init.sh
```

After a while, it asks to create an admin account. Fill your details. Right after that, it raises the following error

```
Loaded your LOCAL configuration at [/home/work/incubator-superset/superset/superset_config.py]
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
+ superset load_examples
Loaded your LOCAL configuration at [/home/work/incubator-superset/superset/superset_config.py]
Usage: superset [OPTIONS] COMMAND [ARGS]...
Try "superset --help" for help.

Error: No such command "load_examples".
```

**Comment by hajdbo** [comment] 2018-10-25 04:07
see #6167

**Comment by marcotama** [comment] 2018-10-25 04:08
I had the same problem. I resorted to a pip installation, because I was not able to get the Docker installation to work.

**Comment by maxg203** [comment] 2018-10-25 21:14
I noticed a related typo in the installation instructions (see reference above). Would be great if someone could merge these two little open pull requests so that we can close this issue. Docker installation worked well for me otherwise.

**Comment by mistercrunch** [comment] 2018-10-26 04:07
Merged both PR, the issue is around the `click` library making backwards incompatible changes as to how they manage `_` vs `-`

**Closed** 2018-10-26 05:00 UTC
