### ISSUE TITLE
Cursor falls behind in SQL Lab

### ISSUE THREAD

**Issue by etr2460** [apache/incubator-superset#9253] opened 2020-03-07 01:12 UTC
When typing in SQL Lab, the cursor slowly falls behind the characters.

### Expected results

Typing to be normal

### Actual results

![cursor falls behind](https://user-images.githubusercontent.com/7409244/76133512-5360ab00-5fcd-11ea-90a6-c684b4086154.gif)

#### How to reproduce the bug

Type a longish line in SQL Lab

### Environment

(please complete the following information):

- superset version: master
- browser: latest Chrome

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I suspect this is related to the change that was made to fix cursor position in Safari. I then think the issue was exacerbated by the new font in SQL Lab. This seems likely as we saw a report from a user that the cursor was messed up in Chrome prior to rolling out the new fonts, but with the new font it's way more obvious and happens way more often

cc: @rusackas @nytai

**Comment by rusackas** [comment] 2020-03-07 01:34
Awww man! I agree with your assessment, but don't yet know the root cause. Investigating...

**Comment by willbarrett** [comment] 2020-03-09 16:46
@rusackas I think you pushed a fix for this?

**Comment by etr2460** [comment] 2020-03-09 16:50
@willbarrett I sent a chat to Evan, I think this is likely caused by his first fix :(

**Comment by willbarrett** [comment] 2020-03-09 16:52
Oh no! 😢

**Comment by rusackas** [comment] 2020-03-09 17:21
Submitted a PR reverting that earlier fix. Seems to work in both browsers now that the new font is in. Sunk some time last night into trying to upgrade ACE editor (which also fixes this), but that started getting too hairy, so I pulled the ripcord on that. Please sanity check that PR and make sure the issue is really gone :)

**Closed** 2020-03-09 19:46 UTC

**Comment by mapshen** [comment] 2021-07-15 20:25
Hi all, we are running `apache/superset:257385e888c5f9530882c62a20981bfd00e83009` which is a build pushed a few days ago in docker and we now are experiencing the same issue as @etr2460 described. Would any of you be able to take a look?

**Comment by mapshen** [comment] 2021-07-16 16:31
I just tested with the latest build with `docker pull apache/superset:66c28d653f3f9381479ab817e6dba8f6598d8b8d` and can confirm the issue is there. 

@rusackas Would you have time to take a look? Thanks!

**Comment by junlincc** [comment] 2021-07-23 19:04
@geido users reported this is happening again. We fixed the editor in Explore, but im not able to reproduce in SQL lab. could you take a look?

**Comment by ayushbilala** [comment] 2022-01-27 09:29
I am on Superset 1.3.2 and able to replicate the issue on Windows OS.
Font style is very different and clean in Mac though. Can we please expect a fix for this?

**Comment by shreyaUp** [comment] 2022-01-27 09:44
> I am on Superset 1.3.2 and able to replicate the issue on Windows OS. Font style is very different and clean in Mac though. Can we please expect a fix for this?

Same here. A fix would really help!

**Comment by shumway743** [comment] 2022-04-06 20:03
We are also experiencing this with the latest release. The issue seems to be related to syntax highlighting. If you type "select select select ..." all the way across the screen you will see the cursor lag (select is bolded as it is a keyword). If you type a non-keyword such as "hello hello hello ..." across the window, the cursor seems to keep up fine (no bolding takes place). Just an observation.

**Comment by LuPan2015** [comment] 2022-06-17 04:09
I had the same problem with superset 1.4.0. Details are as follows:
```
SELECT
    database,
    table,
    partition,
    sum(rows) AS rows,
    count() AS part_count
FROM system.parts
WHERE (active = 1) AND (table ='game_match_log') AND (database ='gem') and partition =  ''
GROUP BY
    database,
    table,
    partition
ORDER BY part_count DESC;
limit 30;
```

https://user-images.githubusercontent.com/10804128/174222924-b61f595e-59cb-467d-b00e-662196fd242f.mp4

**Comment by ubyyj** [comment] 2022-07-17 08:41
same issue here, 1.4.0 in Chrome

**Comment by drummerwolli** [comment] 2022-09-01 07:23
Issue seems to be still prominent, especially on Windows machines, on 2.0.0 ...

**Comment by MichaelHintz** [comment] 2022-09-07 18:37
For me, opening the developer tools and disabling `font-family: Menlo,Lucida Console,Courier New,Ubuntu Mono,Consolas,source-code-pro,monospace` or at least removing `Lucida Console` is fixing the issue, as described in:

https://github.com/apache/superset/issues/19094#issuecomment-1235702599
https://github.com/apache/superset/pull/9183#issuecomment-624204443
https://github.com/apache/superset/issues/15749#issuecomment-1174574502

The problem seems to be that `Lucida Console` doesn't have a bold version on Windows, so Windows tries to make it bold by making it wider.

[1] https://github.com/wez/wezterm/issues/2074#:~:text=Lucida%20Console%20is%20a%20preinstalled%20font%20in%20Windows.%20It%20does%20not%20have%20a%20built%20in%20bold%20version.%20Compare%20with%20Courier%20New%3A

[2] https://forums.allroundautomations.com/ubb/ubbthreads.php?ubb=showflat&Number=29702#:~:text=issue%20with%20in%20the%20font

[3] https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#:~:text=5.05-,Lucida%20Console,-Lucida%20Console


`Consolas` and `Courier New` both come with bold versions on windows. Any chance `Consolas` can be moved https://github.com/apache/superset/blob/ce3d38d2e72a56014fa96ee3d4afe066277cc5be/superset-frontend/src/SqlLab/main.less#L370-L371 before `Lucida Console`? 

Another 'fix' that I can confirm is uninstalling `Lucida Console` from Windows. 


All related issues and PRs I could find:
https://github.com/apache/superset/issues/9253
https://github.com/apache/superset/issues/15749
https://github.com/apache/superset/issues/19094
https://github.com/apache/superset/issues/19580
https://github.com/apache/superset/issues/20436

https://github.com/apache/superset/pull/9183
https://github.com/apache/superset/pull/9264
https://github.com/apache/superset/pull/12423
