### ISSUE TITLE
Can i move the dashboards created from 1 server to another 

### ISSUE THREAD

**Issue by mohanguruswamy** [apache/incubator-superset#498] opened 2016-05-20 11:25 UTC
Hi 

I have created few dashboard in 1 of the Dev machine, i want to move the dashboards created into another machine where i should be able to use the reports with same DB-Table structure .

Is this possible.

Thanks
Mohan

**Comment by sivackrishna** [comment] 2017-11-06 06:31
I am looking for the solution. Any one has idea on this.

**Comment by xrmx** [comment] 2017-11-06 08:30
We have import and export of dashboard since a few, i think we can close this.

**Comment by sivackrishna** [comment] 2017-11-06 08:31
Will you please tell me how to import and export of dashboards

**Comment by mistercrunch** [comment] 2017-11-07 07:35
<img width="586" alt="screen shot 2017-11-06 at 11 35 03 pm" src="https://user-images.githubusercontent.com/487433/32482131-276a0e18-c34b-11e7-9e2f-3093e49cfdfc.png">

**Comment by mistercrunch** [comment] 2017-11-07 07:36
<img width="368" alt="screen shot 2017-11-06 at 11 35 39 pm" src="https://user-images.githubusercontent.com/487433/32482151-3e41a0d8-c34b-11e7-89d5-526f6c81cdca.png">

**Comment by sivackrishna** [comment] 2017-12-29 08:56
Still, I'm also facing the Issue.
I have designed some dashboards in development machine (Ex: System1). I want to import the same dashboards in Client machine (Ex: System2).

Getting following error, When we export the dashboards from System1 and import into System2

> Sorry, something went wrong
> 500 - Internal Server Error
> Stacktrace
>          Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/local/lib/python2.7/dist-packages/superset/models/core.py", line 870, in wrapper
>     value = f(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/superset/utils.py", line 624, in wraps
>     return f(self, *args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/superset/views/core.py", line 1054, in import_dashboards
>     ds_class.import_obj(table, import_time=current_tt)
>   File "/usr/local/lib/python2.7/dist-packages/superset/connectors/sqla/models.py", line 703, in import_obj
>     import_time)
>   File "/usr/local/lib/python2.7/dist-packages/superset/import_util.py", line 23, in import_datasource
>     i_datasource.database_id = lookup_database(i_datasource).id
>   File "/usr/local/lib/python2.7/dist-packages/superset/connectors/sqla/models.py", line 700, in lookup_database
>     database_name=table.params_dict['database_name']).one()
>   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2820, in one
>     raise orm_exc.NoResultFound("No row was found for one()")
> NoResultFound: No row was found for one()

Are the users should be same on both the machines?
If it is datasource problem, I have created the same datasource as per the System1. Still the problem is there

Will you please suggest me how to use export and import functionality across the Machines?

Thanks in Advance

**Closed** 2019-02-07 07:28 UTC
Labels: #feature
