### ISSUE TITLE
I am unable to add a postgres database

### ISSUE THREAD

**Issue by Nathandrake01** [apache/incubator-superset#9434] opened 2020-04-01 11:13 UTC
I am unable to add a postgres database, on web browser when I check it it says ok but when i click save it says:

'NoneType' object has no attribute 'encode'

**Comment by villebro** [comment] 2020-04-01 11:26
Thanks @Nathandrake01 , this is a duplicate of #9430 , we will be posting a fix shortly.

**Comment by eugeniamz** [comment] 2020-04-01 21:44
is there a work around this ?

**Closed** 2020-04-02 05:17 UTC
