### ISSUE TITLE
TableViz raise Unexpected error when table include null value

### ISSUE THREAD

**Issue by Wujiao233** [apache/incubator-superset#5604] opened 2018-08-11 02:26 UTC
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

when table include number type columns and the value is `null` , The TableViz cannot display this table when these columns be selected in `NOT GROUPED BY`

### Superset version
0.26.3 On centos7  + Python 3.6.5

### Actual results
Unexpected error.

### Steps to reproduce

Table DDL:
`
CREATE TABLE testt (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  value int(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;
`
Data:

|id|name|value|
|-|-|-|
|1|aaa|1|
|2|bbb||
|3|ccc|3|
|4|ddd||

And choose these three columns in TableViz's `NOT GROUPED BY` selector.

**Comment by villebro** [comment] 2018-08-11 05:15
This is a duplicate of #5353

**Comment by villebro** [comment] 2018-08-11 06:14
@Wujiao233 This was reported on `0.26.3` but the PR is against `master`, can you verify that you are able to get the same error on `master` also?

**Comment by Wujiao233** [comment] 2018-08-11 10:47
the `master` is ok...but i think it's not a good idea to fill number type `null` to `0` .In some case `null` is not mean `0` .

**Comment by villebro** [comment] 2019-04-11 05:54
@Wujiao233 this issue has been resolved and can be closed

**Closed** 2019-04-11 06:02 UTC
