### ISSUE TITLE
Oracle "ORA-00907: missing right parenthesis" error #4058

### ISSUE THREAD

**Issue by umesh11111** [apache/incubator-superset#9237] opened 2020-03-04 15:47 UTC
Getting Oracle "ORA-00907: missing right parenthesis" error #4058
error while creating the datasource.
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- npm version: `npm -v`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by dpgaspar** [comment] 2020-03-04 15:54
Hi @umesh11111,

That's a very old issue, can you please update your issue environment fields? (superset version, python version, etc...)

**Comment by umesh11111** [comment] 2020-03-04 15:56
superset version---0.33.010402
Python version----3.7

**Comment by umesh11111** [comment] 2020-03-04 15:57
> Hi @umesh11111,
> 
> That's a very old issue, can you please update your issue environment fields? (superset version, python version, etc...)

Hi @dpgaspar 

superset version---0.33.010402
Python version----3.7

**Comment by dpgaspar** [comment] 2020-03-04 16:03
Thank you, this seems to have been fixed on #4058 that shipped with superset 0.23.
Can you give a more detailed information, steps to reproduce, ORACLE version

@villebro can you reproduce this?

**Comment by villebro** [comment] 2020-03-04 16:28
No, unfortunately not, because this ticker uncovered another regression for Oracle, probably caused by the Pandas -> Arrow migration:
![image](https://user-images.githubusercontent.com/33317356/75900569-c7704700-5e45-11ea-954b-57cbede1e6cf.png)
I can look into this, might be a quick fix.

**Closed** 2020-03-04 21:43 UTC
