### ISSUE TITLE
SQL Lab does not load temp table names in spark SQL

### ISSUE THREAD

**Issue by rezabaktash** [apache/incubator-superset#3263] opened 2017-08-09 08:10 UTC
Hi, 
I am using Superset 0.19.0 to connect Spark Sql. I need to query my temp tables in spark. The database is created and connection is OK. I also was able to create a table by selecting my database connection and giving the table name and empty schema name ( Spark temp tables don't have a database/schema ). I am able to load data from my table and visualize it.
![tables1](https://user-images.githubusercontent.com/8961517/29110753-087f6564-7cfd-11e7-9923-a75c5b7ae381.png)

Now I want to query my tables from SQL Lab, but I can't access the tables. The reason is that If I don't select any schema, I can't see or search my table names. 

![sqllab](https://user-images.githubusercontent.com/8961517/29111287-e4d5933e-7cfe-11e7-95ac-fd228b08c129.png)

Is it possible to make SQL Lab view and query tables which are NOT in any database/schema?

**Comment by xrmx** [comment] 2017-08-16 15:07
Isn't this a duplicate of #3247 ?

**Comment by rezabaktash** [comment] 2017-08-16 15:38
Sure it is. I will follow that. Thanks!

**Comment by xrmx** [comment] 2017-08-16 15:42
Please close this one then, thanks!

**Closed** 2017-08-16 15:42 UTC
