### ISSUE TITLE
Enable to start with apache superset .. when trying to run the command docker-compose up ..File "/usr/local/lib/python3.6/urllib/request.py".py,line 1361,in https_open superset-init_1 | context=self._context,check_hostname=self._check_hostname) superset-init_1 | File "/usr/local/lib/python3.6/urllib/request.py", line 1283 , in do_open superset_init_1 | raise URLError('no host given') superset_init_1  | urllib.error.URLError: <urlopen error no host given >

### ISSUE THREAD

**Issue by Michael3190** [apache/incubator-superset#9553] opened 2020-04-16 06:43 UTC
Docker-compose error

**Comment by dpgaspar** [comment] 2020-04-16 13:23
duplicate of #9554

**Closed by dpgaspar** 2020-04-16 13:23 UTC
Labels: need:more-info
