### ISSUE TITLE
Installed in .pyenv but, cannot serve via SSL

### ISSUE THREAD

**Issue by jerryhall** [apache/incubator-superset#3103] opened 2017-07-10 21:10 UTC
My superset is installed on my AWS EC2 instance in:
 /home/ec2-user/.pyenv/versions/2.7.12/lib/python2.7/site-packages

And my SSL is serving my /var/www/ securely on this same server. I created a webpage to display the dashboard in an iframe but, cannot get it to appear because of a mixed-content warning - not being able to display insecure content on a secure page. 

How would I display my dashboards on a such a secure page when my python is in the server user account but, my website is in a SSL-enabled web area?

Thanks for any help!

**Comment by xrmx** [comment] 2017-07-11 07:35
Duplicate of #533, TLDR; use nginx in front of it or use plain gunicorn options instead of using superset wrapper.

**Closed** 2017-08-20 22:12 UTC
