### ISSUE TITLE
[landing page] Click "Favorite" link throw JS error

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/incubator-superset#11567] opened 2020-11-05 00:55 UTC
### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### How to reproduce the bug

1. Go to Superset landing page
2. Click on 'Favorite' link on dashboard or chart section
3. See JS error and whole page is blank.

#### Screenshots

![KOhBQDDCFV](https://user-images.githubusercontent.com/27990562/98184086-614d2f80-1ebe-11eb-852e-8243dc6bca9e.gif)

### Environment

(please complete the following information):

- superset version: latest 

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment] 2020-11-05 01:52
![ezgif-7-13f2cba903ea](https://user-images.githubusercontent.com/67837651/98187678-572f2f00-1ec6-11eb-8163-99c0decc8326.gif)
it's working alright from my end. im not able to reproduce 😞

**Comment by s1aw1k** [comment] 2020-11-05 05:02
![image](https://user-images.githubusercontent.com/73978786/98199819-f1868580-1f4d-11eb-9bb2-a360438cf975.jpeg)

**Comment by junlincc** [comment] 2020-11-05 05:09
update, @pkdotson is working on the issue, there is a case when first name and last name doesn’t exist

**Comment by junlincc** [comment] 2020-11-09 18:35
[chore(home-screen): fixes for loading states, flicker issue, and reduction of api calls #11557 
](https://github.com/apache/incubator-superset/pull/11557) closing

**Closed by junlincc** 2020-11-09 18:35 UTC
Labels: #bug
